In [65]:
import customfunctions as ctf
import pandas as pd
import numpy as np
import scipy.signal as signal
import heartpy as hp
import neurokit2 as nk
import prepro as prep  # Custom functions for preprocessing
import matplotlib.pyplot as plt
import os
import glob
from pathlib import Path
from scipy.ndimage import uniform_filter1d

# Parameters

### Preprocessing parameters

In [66]:
# BVP preprocessing
bvp_prepro_winsz = 10
bvp_prepro_ovlap = 0.02
bvp_fs = 64

# EDA preprocessing
eda_fs = 4
iter_num = 7

### Processing parameters

In [67]:
basalscene = 0
targetscene = 4
# Note, subject 10 does not have scene 2 nor 3 data
subjects = [1, 2, 3, 4, 6, 8, 9, 10]
winsz = 60
ovlap = 0.5
base_dir = Path().resolve()

# Data import function

In [ ]:
folderpath = os.path.join(base_dir, "..", "RawData")
folderpath = os.path.abspath(folderpath)


def dataimport(subjects, folderpath, scene):
    bvp_rawdata_list = []
    eda_rawdata_list = []

    for subject in subjects:
        subject_str = f"S{subject}" if subject == 10 else f"S{subject:02d}"
        pattern = os.path.join(
            folderpath,
            f"S{subject}",
            "Empatica",
            f"P300_{subject_str}R0{scene}*",
            "Raw",
        )
        matched_folders = glob.glob(pattern)
        raw_folder = matched_folders[0]
        bvp_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileBVP.csv")).drop(
            "Datetime", axis=1
        )
        eda_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileEDA.csv")).drop(
            "Datetime", axis=1
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_rawdata_list.append(bvp_dataholder)
        eda_rawdata_list.append(eda_dataholder)

    bvp_rawdata_df = pd.concat(bvp_rawdata_list, ignore_index=True)
    eda_rawdata_df = pd.concat(eda_rawdata_list, ignore_index=True)

    return bvp_rawdata_df, eda_rawdata_df


basal_bvp_rawdata, basal_eda_rawdata = dataimport(
    subjects, folderpath, scene=basalscene
)
tscene_bvp_rawdata, tscene_eda_rawdata = dataimport(
    subjects, folderpath, scene=targetscene
)

1 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S1\\Empatica\\P300_S01R00_29042024_1237\\Raw']
2 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S2\\Empatica\\P300_S02R00_29042024_1342\\Raw']
3 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S3\\Empatica\\P300_S03R00_29042024_1628\\Raw']
4 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S4\\Empatica\\P300_S04R00_30042024_0945\\Raw']
6 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S6\\Empatica\\P300_S06R00_30042024_1632\\Raw']
8 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S8\\Empatica\\P300_S08R00_02052024_1206\\Raw']
9 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S9\\Empatica\\P300_S09R00_02052024_1611\\Raw']
10 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S10\\Empatica\\P300_S10R00_03052024_1026\\Raw']
1 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S1\\Empatica\\P300_S01R04_29042024_1310\\Raw']
2 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S2\\Empatica\\P300_S02R04_29042024_1409\\Raw']
3 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S3\\Empatica\\P300_S03R04_29042024_1659\\Raw']
4 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S4\\Empatica\\P300_S04R04_30042024_1019\\Raw']
6 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S6\\Empatica\\P300_S06R04_30042024_1627\\Raw']
8 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S8\\Empatica\\P300_S08R04_02052024_1230\\Raw']
9 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S9\\Empatica\\P300_S09R04_02052024_1637\\Raw']
10 ['C:\\Users\\josee\\OneDrive\\Documentos\\GitHub\\neurohumanities-lab\\OfflineProcessing\\RawData\\S10\\Empatica\\P300_S10R04_03052024_1055\\Raw']

# Preprocessing function

In [69]:
def preprocess(subjects, bvp_df, eda_df, bvp_fs, eda_fs, winsz, ovlap, iter_num):
    bvp_prepdata_list = []
    eda_prepdata_list = []
    for subject in subjects:
        bvp_dataholder = pd.DataFrame(
            prep.preprocess_bvp(
                sig=bvp_df[bvp_df["Subject"] == subject]["valueBVP"],
                fs=bvp_fs,
                winsz=winsz,
                ovlap=ovlap,
            ),
            columns=["valueBVP"],
        )
        eda_dataholder = pd.DataFrame(
            prep.preprocess_eda(
                sig=eda_df[eda_df["Subject"] == subject]["valueEDA"],
                fs=eda_fs,
                iter_num=iter_num,
                verbose=False,
            )[0],
            columns=["valueEDA"],
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_prepdata_list.append(bvp_dataholder)
        eda_prepdata_list.append(eda_dataholder)

    bvp_prepdata_df = pd.concat(bvp_prepdata_list, ignore_index=True)
    eda_prepdata_df = pd.concat(eda_prepdata_list, ignore_index=True)

    return bvp_prepdata_df, eda_prepdata_df


basal_bvp_prepdata, basal_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=basal_bvp_rawdata,
    eda_df=basal_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

tscene_bvp_prepdata, tscene_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=tscene_bvp_rawdata,
    eda_df=tscene_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

# Processing function

In [70]:
import warnings
def get_bvp_feats(window, smooth_window, fs):
    wd = {}
    wd = hp.peakdetection.detect_peaks(
        window, smooth_window, ma_perc=20, sample_rate=fs
    )
    wd = hp.analysis.calc_rr(wd["peaklist"], sample_rate=fs, working_data=wd)
    wd = hp.peakdetection.check_peaks(
        wd["RR_list"], wd["peaklist"], window[wd["peaklist"]], working_data=wd
    )
    wd = hp.analysis.clean_rr_intervals(working_data=wd, method="quotient-filter")
    rr_list = wd["RR_list_cor"]
    rr_diff = np.diff(rr_list)
    rr_sqdiff = np.power(rr_diff, 2)
    wd, msrs = hp.analysis.calc_ts_measures(
        rr_list, rr_diff, rr_sqdiff, working_data=wd
    )
    wd, msrs = hp.analysis.calc_fd_measures(measures=msrs, working_data=wd)
    bvp_feats = pd.DataFrame([msrs])[
        [
            "bpm",
            "sdnn",
            'rmssd',
            "pnn50",
            "hr_mad",
            "lf",
            "hf",
            "lf/hf",
            "p_total",
            "lf_nu",
            "hf_nu",
        ]
    ]

    return bvp_feats


def get_eda_feats(window, fs):
    signals, info = nk.eda_process(window, fs)
    mean_eda = np.nanmean(window)
    mean_tonic = np.nanmean(signals["EDA_Tonic"])
    scr_peak_count = np.nansum(signals["SCR_Peaks"])
    scr_sum_amp = np.nansum(info["SCR_Amplitude"])
    scr_mean_amp = np.nanmean(info["SCR_Amplitude"])
    scr_mean_risetime = np.nanmean(info["SCR_RiseTime"])
    scr_mean_recoverytime = np.nanmean(info["SCR_RecoveryTime"])

    eda_feats = pd.DataFrame(
        [
            {
                "mean_eda": mean_eda,
                "mean_tonic": mean_tonic,
                "scr_peak_count": scr_peak_count,
                "scr_sum_amp": scr_sum_amp,
                "scr_mean_amp": scr_mean_amp,
                "scr_mean_risetime": scr_mean_risetime,
                "scr_mean_recoverytime": scr_mean_recoverytime,
            }
        ]
    )

    return eda_feats


def process(subjects, bvp_prepdata_df, eda_prepdata_df, bvp_fs, eda_fs, ovlap, winsz):
    feat_mat_list = []
    for subject in subjects:
        # BVP
        bvp_probe = np.array(
            bvp_prepdata_df[bvp_prepdata_df["Subject"] == subject]["valueBVP"]
        )
        bvp_smooth = uniform_filter1d(
            bvp_probe, size=int(0.75 * bvp_fs), mode="nearest"
        )
        bvp_windowed = ctf.timewindowpadded(
            data=bvp_probe, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        smooth_windowed = ctf.timewindowpadded(
            data=bvp_smooth, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        bvp_holder_list = []
        for windnum in range(0,bvp_windowed.shape[0]):
            bvp_feat_row = get_bvp_feats(
                window=bvp_windowed[windnum],
                smooth_window=smooth_windowed[windnum],
                fs=bvp_fs,
            )
            bvp_holder_list.append(bvp_feat_row)
        bvp_holder_df = pd.concat(bvp_holder_list, ignore_index=True)

        # EDA
        eda_probe = np.array(
            eda_prepdata_df[eda_prepdata_df["Subject"] == subject]["valueEDA"]
        )
        eda_windowed = ctf.timewindowpadded(
            data=eda_probe, fs=eda_fs, ovlap=ovlap, winsz=winsz
        )
        eda_holder_list = []
        for windnum in range(0,eda_windowed.shape[0]):
            eda_feat_row = get_eda_feats(window=eda_windowed[windnum], fs=eda_fs)
            eda_holder_list.append(eda_feat_row)
        eda_holder_df = pd.concat(eda_holder_list, ignore_index=True)

        valid_len = min(len(bvp_holder_df), len(eda_holder_df))
        joined_df = pd.concat([bvp_holder_df.iloc[:valid_len], eda_holder_df.iloc[:valid_len]], axis=1)
        joined_df.insert(loc=0, column="Subject", value=[subject] * len(joined_df))
        feat_mat_list.append(joined_df)
        
    feat_mat_df = pd.concat(feat_mat_list, ignore_index=True)
    return feat_mat_df


basal_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=basal_bvp_prepdata,
    eda_prepdata_df=basal_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

tscene_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=tscene_bvp_prepdata,
    eda_prepdata_df=tscene_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

warnings.filterwarnings('ignore')

In [71]:
basal_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,60.826446,53.793024,63.233543,0.155556,31.2500,924.116936,1170.473541,0.789524,2.094590e+03,44.119218,55.880782,-0.008248,-0.008088,10,0.091262,0.009126,0.425000,0.678571
1,1,63.605067,74.064890,75.324817,0.160000,46.8750,1409.887040,930.381341,1.515386,2.340268e+03,60.244673,39.755327,-0.001568,-0.001620,13,0.078395,0.006030,0.423077,0.642857
2,1,63.691194,56.350347,58.694936,0.148148,31.2500,686.325269,826.141762,0.830760,1.762398e+03,45.377866,54.622134,-0.000471,-0.000526,11,0.095344,0.008668,0.545455,0.750000
3,1,67.467057,122.776171,115.788412,0.127660,62.5000,1975.783853,1136.872088,1.737912,3.112656e+03,63.475819,36.524181,-0.000456,-0.000566,12,0.080819,0.007347,1.250000,1.375000
4,1,71.831645,106.115797,116.904579,0.127660,85.9375,1485.146287,984.318328,1.508807,2.469465e+03,60.140416,39.859584,0.003984,0.003746,22,0.079369,0.003779,0.916667,0.750000
5,1,66.804951,62.836413,55.995817,0.156863,46.8750,579.078261,1834.289281,0.315696,2.413368e+03,23.994615,76.005385,0.014380,0.014300,12,0.111295,0.009275,0.770833,1.111111
6,2,68.534343,52.880012,45.780491,0.092308,31.2500,292.261292,412.743283,0.708095,8.482538e+02,41.455233,58.544767,-0.036505,-0.036688,56,0.330408,0.006007,0.422727,0.500000
7,2,73.079585,90.994130,62.379692,0.123077,46.8750,1996.809797,1346.703264,1.482739,4.498593e+03,59.721908,40.278092,-0.006954,-0.007078,57,0.326441,0.005829,0.370536,0.527778
8,2,74.517890,82.447269,58.595817,0.079365,46.8750,385.864356,757.807670,0.509185,3.164651e+03,33.739074,66.260926,0.005557,0.005445,51,0.293340,0.005752,0.450980,0.583333
9,2,76.072351,74.892770,43.580620,0.029412,62.5000,820.606860,348.138072,2.357130,1.608311e+03,70.212656,29.787344,0.003289,0.003127,51,0.330304,0.006477,0.450980,0.576923
10,2,80.551033,78.816347,71.110268,0.136364,46.8750,802.311184,276.142146,2.905428,1.078453e+03,74.394613,25.605387,-0.000217,-0.000732,19,0.339743,0.017881,0.539474,0.865385
11,2,83.097950,90.150986,80.515871,0.196429,62.5000,2654.964520,2208.899004,1.201940,4.863864e+03,54.585506,45.414494,0.000126,0.000083,16,0.314013,0.019626,0.625000,1.045455
12,3,80.919540,58.925022,57.855825,0.157895,46.8750,753.699014,1513.675259,0.497926,2.359554e+03,33.241050,66.758950,0.001535,0.001471,25,0.128168,0.005127,0.490000,0.568182
13,3,83.321725,48.993876,48.096075,0.087500,31.2500,1002.316980,1286.456343,0.779130,2.411862e+03,43.792759,56.207241,-0.000475,-0.000435,22,0.115962,0.005271,0.431818,0.500000
14,3,85.333333,41.265977,39.739000,0.063291,31.2500,578.276098,682.581080,0.847190,1.450552e+03,45.863727,54.136273,-0.000906,-0.000834,23,0.101045,0.004393,0.434783,0.546875
15,3,89.751888,81.050620,99.129512,0.109375,31.2500,713.470738,1159.049948,0.615565,1.872521e+03,38.102155,61.897845,-0.001100,-0.001131,28,0.162712,0.006026,0.453704,0.607143
16,3,98.969072,136.478211,157.064638,0.136364,31.2500,356.334344,1733.118155,0.205603,2.089452e+03,17.053958,82.946042,-0.001320,-0.001312,25,0.183404,0.007336,0.580000,0.500000
17,3,104.973545,156.238618,178.654185,0.166667,62.5000,1494.278308,2907.209625,0.513991,4.401488e+03,33.949390,66.050610,0.006304,0.006184,26,0.167011,0.006424,0.625000,0.750000
18,4,72.000000,37.327306,47.669548,0.092308,31.2500,165.573854,1112.308459,0.148856,1.291142e+03,12.956894,87.043106,-0.038242,-0.038484,34,0.182703,0.005374,0.617647,0.826923
19,4,72.654424,45.732453,52.312153,0.104478,39.0625,478.627662,1591.048774,0.300825,2.184727e+03,23.125724,76.874276,-0.000683,-0.000662,36,0.169557,0.004710,0.611111,0.750000
20,4,73.011849,46.558323,54.490190,0.088235,31.2500,251.455587,1295.280283,0.194132,1.621821e+03,16.257177,83.742823,0.001566,0.001522,40,0.199825,0.004996,0.506250,0.409091
21,4,74.909964,65.966199,76.271969,0.171875,46.8750,778.518614,1181.564330,0.658888,1.985198e+03,39.718657,60.281343,-0.000178,-0.000179,40,0.210344,0.005259,0.537500,0.472222
22,4,84.819277,92.220215,83.470940,0.215385,46.8750,581.677463,639.274873,0.909902,1.220952e+03,47.641292,52.358708,0.005153,0.003417,4,1.292520,0.323130,0.875000,1.000000
23,4,86.066933,73.133805,63.201360,0.152778,46.8750,543.397540,555.476494,0.978255,2.667378e+03,49.450394,50.549606,0.040026,0.040583,4,1.294187,0.323547,0.875000,2.250000
24,6,100.237304,144.743133,113.512993,0.333333,109.3750,5034.980949,5299.509394,0.950084,1.033449e+04,48.720167,51.279833,-0.008204,-0.011528,7,0.246131,0.035162,1.071429,2.041667
25,6,106.175115,160.721605,137.041608,0.264151,54.6875,4370.813549,9998.534220,0.437145,1.436935e+04,30.417620,69.582380,0.000121,0.000064,33,0.273017,0.008273,0.401515,0.500000
26,6,113.136915,145.770243,128.695377,0.200000,31.2500,2035.281240,14124.058282,0.144100,1.615934e+04,12.595077,87.404923,-0.000535,-0.000647,54,0.329292,0.006098,0.407407,0.403846
27,6,92.464589,194.008587,129.866217,0.220000,171.8750,7363.760414,3646.991102,2.019133,1.101075e+04,66.877909,33.122091,0.000317,0.000512,34,0.237592,0.006988,0.500000,0.541667
28,6,77.005348,120.022423,158.558935,0.272727,46.8750,1178.067569,1312.024354,0.897901,2.490092e+03,47.310204,52.689796,-0.000441,-0.000304,28,0.260934,0.009319,0.517857,0.850000
29,6,87.721302,163.708230,170.320035,0.282051,101.5625,3901.455452,13801.959997,0.282674,1.770342e+04,22.037869,77.962131,0.044063,0.043338,4,0.951253,0.237813,1.875000,2.500000
30,8,77.679389,65.768699,96.538069,0.250000,31.2500,285.001876,2045.411960,0.139337,2.330414e+03,12.229668,87.770332,0.139464,0.144337,5,3.297152,0.659430,1.500000,1.625000
31,8,80.313725,53.479616,70.374477,0.142857,31.2500,247.922990,313.281532,0.791374,5.612045e+02,44.176941,55.823059,0.117056,0.118170,7,5.298295,0.756899,1.678571,3.333333
32,8,81.626617,54.285517,57.970026,0.161765,31.2500,877.383331,1132.437957,0.774774,2.009821e+03,43.654793,56.345207,0.034594,0.037049,8,4.988673,0.623584,1.562500,1.535714
33,8,82.118126,70.303642,71.189092,0.161290,31.2500,2256.734064,967.008431,2.333727,3.223742e+03,70.003546,29.996454,-0.015150,-0.022870,8,3.987338,0.569620,1.607143,1.812500
34,8,84.359949,104.208793,129.032683,0.235294,62.5000,2611.785720,2470.937270,1.057002,5.082723e+03,51.385561,48.614439,0.069577,0.066567,6,3.606154,0.601026,1.583333,2.000000
35,8,84.498778,111.392872,138.598082,0.250000,78.1250,2412.565662,3842.802125,0.627814,6.255368e+03,38.567927,61.432073,0.302449,0.300636,5,2.731687,0.546337,1.400000,6.500000
36,9,84.327799,39.962581,36.292613,0.049383,31.2500,68.430908,331.766636,0.206262,5.131799e+02,17.099282,82.900718,0.432206,0.433477,16,1.980106,0.123757,0.609375,1.000000
37,9,86.713131,38.838832,42.035316,0.050000,31.2500,210.696150,962.951552,0.218802,1.247384e+03,17.952248,82.047752,0.044844,0.049875,11,2.429369,0.220852,0.931818,1.000000
38,9,89.134253,78.703800,94.672968,0.082192,31.2500,434.897818,1040.565284,0.417944,1.475463e+03,29.475344,70.524656,0.026938,0.027426,11,2.775823,0.252348,1.068182,0.944444
39,9,88.779285,86.191607,96.370334,0.094595,31.2500,689.813882,4096.520151,0.168390,5.865412e+03,14.412155,85.587845,-0.135594,-0.128230,9,1.832838,0.203649,1.055556,0.964286
40,9,90.700057,56.844929,47.724767,0.109756,31.2500,280.768398,401.258060,0.699720,9.919040e+02,41.166790,58.833210,-0.727980,-0.726550,22,1.935108,0.087959,0.602273,0.681818
41,9,98.226467,62.195787,49.875796,0.135135,31.2500,428.800323,300.844096,1.425324,7.296444e+02,58.768396,41.231604,-2.862017,-2.856951,11,7.174423,0.652220,1.022727,2.750000
42,10,85.714286,57.635188,52.480581,0.140625,46.8750,951.590266,1607.125080,0.592107,2.558715e+03,37.190157,62.809843,0.322412,0.321084,3,0.054784,0.018261,0.583333,6.000000
43,10,87.402985,95.352965,123.361659,0.150000,46.8750,2275.494030,2018.183014,1.127496,4.293677e+03,52.996395,47.003605,0.694390,0.694265,32,0.311434,0.009732,0.531250,0.708333
44,10,91.838565,123.800242,113.870891,0.142857,46.8750,1059.462856,1709.130320,0.619884,2.768593e+03,38.267192,61.732808,0.540885,0.541632,23,0.269207,0.011705,0.532609,0.892857
45,10,95.379381,112.406836,79.842238,0.138889,62.5000,7676.733061,3178.409770,2.415275,1.085514e+04,70.719779,29.280221,0.208208,0.209078,11,0.682289,0.062026,0.818182,1.000000
46,10,92.753623,71.286654,64.543339,0.151899,46.8750,483.758952,144.179527,3.355254,1.122338e+03,77.039227,22.960773,0.039266,0.039418,12,0.735301,0.061275,0.854167,1.642857
47,10,89.376559,43.959852,40.367873,0.036145,15.6250,8031.527273,857858.326196,0.009362,1.315152e+10,0.927546,99.072454,0.281750,0.284312,1,0.672188,0.672188,5.750000,NaN

In [72]:
tscene_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,80.457143,163.006056,191.153639,0.428571,140.6250,3.172751e+03,1.281359e+04,0.247608,1.598634e+04,19.846642,80.153358,-0.064255,-0.066151,6,0.651519,0.130304,0.450000,0.375000
1,1,82.997118,137.342081,210.088403,0.428571,109.3750,0.000000e+00,6.245153e+03,0.000000,6.245153e+03,0.000000,100.000000,-0.000356,-0.000200,5,1.180030,0.236006,0.450000,NaN
2,1,91.428571,193.228465,311.633844,0.285714,171.8750,0.000000e+00,1.219651e+04,0.000000,1.219651e+04,0.000000,100.000000,-0.006593,-0.005168,6,0.711107,0.118518,0.875000,0.750000
3,1,90.423862,145.557775,216.948899,0.285714,125.0000,0.000000e+00,3.645333e+03,0.000000,3.645333e+03,0.000000,100.000000,-0.000781,-0.000967,9,0.135318,0.015035,1.166667,0.916667
4,1,100.800000,155.944997,208.463501,0.350000,93.7500,0.000000e+00,8.326933e+03,0.000000,8.326933e+03,0.000000,100.000000,0.001036,0.001210,11,0.167177,0.015198,0.863636,1.468750
5,1,81.355932,141.421356,182.524033,0.375000,140.6250,1.728348e+03,3.353294e+03,0.515418,5.081642e+03,34.011600,65.988400,-0.011342,-0.010631,11,0.303391,0.027581,0.772727,1.062500
6,2,78.837650,61.514043,66.892749,0.140625,31.2500,8.294160e+02,8.914498e+02,0.930412,1.720866e+03,48.197599,51.802401,0.013959,0.014282,36,0.288217,0.008235,0.521429,0.634615
7,2,77.796771,80.830459,80.108743,0.222222,62.5000,1.124317e+03,1.324564e+03,0.848820,2.448880e+03,45.911459,54.088541,0.020214,0.020313,3,1.203188,0.401063,0.333333,1.250000
8,2,75.730858,81.633482,69.169556,0.164179,54.6875,1.908573e+03,8.530462e+02,2.237362,4.208119e+03,69.110652,30.889348,0.036361,0.036194,5,1.779073,0.355815,0.450000,1.250000
9,2,74.366197,56.509579,51.018768,0.138462,39.0625,1.237454e+03,3.443531e+02,3.593561,1.861208e+03,78.230396,21.769604,0.007653,0.007455,5,0.630056,0.126011,0.450000,6.250000
10,2,75.904083,89.574762,84.360531,0.200000,31.2500,6.611924e+10,9.992675e+11,0.066168,1.065387e+12,6.206126,93.793874,0.002424,0.002387,37,0.214675,0.005802,0.412162,0.729167
11,2,79.233604,110.681147,128.086885,0.218182,31.2500,2.632568e+03,4.851458e+03,0.542634,7.484026e+03,35.175825,64.824175,0.070923,0.070822,3,0.744548,0.248183,2.083333,1.375000
12,3,83.168317,93.860479,138.774590,0.117647,31.2500,1.124328e+02,5.019313e+03,0.022400,5.131746e+03,2.190926,97.809074,0.130386,0.131385,7,0.787466,0.112495,1.142857,1.800000
13,3,81.895735,81.371585,85.256860,0.090909,31.2500,4.084331e+02,3.223016e+02,1.267239,7.307348e+02,55.893486,44.106514,-0.144756,-0.144926,7,0.725918,0.103703,1.035714,2.650000
14,3,79.275625,38.275241,35.922940,0.071429,31.2500,6.583751e+02,3.132157e+02,2.101986,9.715909e+02,67.762588,32.237412,-0.185426,-0.185006,21,0.332584,0.015837,0.666667,0.472222
15,3,82.665300,120.511025,176.507013,0.146341,31.2500,2.480903e+02,1.549875e+03,0.160071,1.797965e+03,13.798392,86.201608,-0.099628,-0.099519,21,0.215206,0.010248,0.583333,0.535714
16,3,93.250311,159.849242,219.848627,0.236842,46.8750,9.875164e+02,2.900454e+03,0.340470,3.887970e+03,25.399278,74.600722,0.004771,0.000485,3,0.353873,0.117958,2.500000,0.250000
17,3,102.045061,143.329915,193.985072,0.288889,85.9375,2.725308e+02,4.244114e+03,0.064214,4.516645e+03,6.033921,93.966079,0.042950,0.041984,5,1.060844,0.212169,1.300000,4.375000
18,4,82.045534,92.927560,112.763724,0.183333,46.8750,7.778277e+02,1.950122e+03,0.398861,2.727949e+03,28.513276,71.486724,-0.034077,-0.033918,8,0.164049,0.020506,0.437500,0.535714
19,4,79.648983,86.527506,114.485810,0.235294,46.8750,3.447809e+02,1.422910e+03,0.242307,1.767691e+03,19.504595,80.495405,-0.061213,-0.062461,9,0.175659,0.021957,0.468750,0.535714
20,4,82.148384,94.438302,129.565897,0.260870,46.8750,1.260208e+03,4.869081e+03,0.258818,6.129290e+03,20.560430,79.439570,-0.051415,-0.051590,28,0.282970,0.010106,0.500000,0.578125
21,4,81.640091,94.995644,122.760478,0.181818,46.8750,2.539247e+03,2.062144e+03,1.231362,4.601391e+03,55.184326,44.815674,0.000002,0.000102,30,0.283584,0.009779,0.508621,0.604167
22,4,78.742310,95.101657,130.204802,0.220339,31.2500,8.994772e+02,1.995280e+03,0.450802,2.894757e+03,31.072629,68.927371,0.000307,0.000878,32,0.279782,0.008743,0.523438,0.479167
23,4,77.509408,81.180811,103.176417,0.189655,31.2500,1.920909e+03,1.107809e+03,1.733971,3.028719e+03,63.423167,36.576833,0.001900,0.002057,43,0.318552,0.007408,0.511628,0.382353
24,6,68.638284,85.135367,73.534092,0.092593,31.2500,2.745799e+03,2.485627e+03,1.104670,5.231426e+03,52.486624,47.513376,0.336809,0.336906,52,0.242085,0.004655,0.403846,0.571429
25,6,65.207547,34.635308,46.875000,0.113208,31.2500,1.120123e+02,4.934054e+02,0.227019,6.054178e+02,18.501662,81.498338,0.185978,0.186134,36,0.195806,0.005594,0.392857,0.600000
26,6,67.305164,54.959436,55.543224,0.127273,31.2500,5.922013e+02,4.366563e+02,1.356218,1.028858e+03,57.559109,42.440891,0.064234,0.064279,28,0.191068,0.006824,0.392857,0.770833
27,6,68.873096,74.836795,95.560444,0.192308,31.2500,1.239481e+03,1.777231e+03,0.697423,3.016712e+03,41.087154,58.912846,0.003785,0.003922,14,0.252702,0.018050,0.678571,1.475000
28,6,70.755778,71.621843,84.766215,0.224138,46.8750,9.796047e+02,2.133954e+03,0.459056,3.113558e+03,31.462544,68.537456,-0.002990,-0.002746,8,0.302232,0.037779,1.062500,1.178571
29,6,72.000000,60.560174,70.466815,0.186441,31.2500,1.679120e+03,1.667941e+03,1.006702,3.347061e+03,50.167000,49.833000,0.021840,0.016457,7,0.499106,0.071301,1.107143,1.450000
30,8,75.469687,70.706274,82.857726,0.275862,46.8750,1.806142e+03,2.155800e+03,0.837806,3.961942e+03,45.587290,54.412710,0.072880,0.081905,8,4.925339,0.615667,1.375000,2.291667
31,8,76.300103,73.424770,91.132126,0.263158,62.5000,5.181888e+02,2.555074e+03,0.202808,3.073263e+03,16.861190,83.138810,0.016466,0.022637,7,7.276396,1.039485,1.750000,1.958333
32,8,77.854807,68.268002,75.731787,0.229508,46.8750,1.060328e+03,1.869021e+03,0.567317,2.929349e+03,36.196704,63.803296,-0.120665,-0.110567,8,6.110714,0.763839,1.718750,1.678571
33,8,79.879409,50.495650,56.812698,0.117647,31.2500,8.738225e+02,4.127587e+02,2.117030,1.306718e+03,67.918179,32.081821,-0.109001,-0.139577,8,6.546656,0.935237,1.607143,1.666667
34,8,79.232781,54.495765,63.961702,0.128571,31.2500,5.017668e+02,1.184794e+03,0.423505,1.834408e+03,29.750884,70.249116,0.042097,0.033914,6,6.606493,1.101082,1.875000,2.200000
35,8,87.104960,118.797665,104.312488,0.258621,78.1250,6.525266e+02,4.915315e+03,0.132754,5.567842e+03,11.719560,88.280440,0.131091,0.160219,12,18.555010,1.546251,1.250000,2.821429
36,9,91.725155,57.514984,78.883041,0.100000,15.6250,1.793951e+02,4.340630e+02,0.413293,7.726817e+02,29.243249,70.756751,0.050723,0.053362,9,2.536041,0.281782,1.083333,1.437500
37,9,90.120206,36.583381,40.678384,0.049383,15.6250,3.385220e+02,3.559665e+02,0.950994,7.313971e+02,48.744080,51.255920,0.009913,0.011837,10,3.402001,0.378000,1.250000,1.678571
38,9,89.175871,32.220779,41.666667,0.049383,15.6250,1.239012e+02,5.266684e+02,0.235255,6.767612e+02,19.045037,80.954963,0.018266,0.015959,10,3.662121,0.366212,0.975000,1.875000
39,9,89.410342,32.629466,40.436366,0.052632,15.6250,1.286167e+02,2.997598e+03,0.042907,1.302785e+07,4.114136,95.885864,-0.023327,-0.024284,14,4.472157,0.319440,0.910714,0.800000
40,9,90.937796,46.531613,50.793430,0.094595,31.2500,2.546918e+02,3.505444e+02,0.726561,6.052362e+02,42.081395,57.918605,0.023933,0.023221,15,7.198457,0.479897,0.850000,1.142857
41,9,91.723693,54.631627,60.846052,0.150685,31.2500,1.140169e+03,7.667837e+02,1.486950,1.906953e+03,59.790109,40.209891,0.131414,0.125701,21,13.695774,0.652180,0.702381,0.800000
42,10,74.055587,47.880207,69.011333,0.149254,31.2500,2.366231e+02,1.113095e+03,0.212581,1.430605e+03,17.531305,82.468695,0.104169,0.106851,10,3.800277,0.380028,1.325000,1.031250
43,10,76.153219,46.833444,56.666810,0.125000,31.2500,2.019443e+02,4.617491e+02,0.437346,8.036176e+02,30.427352,69.572648,0.193565,0.197994,7,1.983284,0.283326,1.321429,1.166667
44,10,78.260870,41.718717,41.776495,0.094595,31.2500,6.667061e+02,4.770979e+02,1.397420,1.249587e+03,58.288491,41.711509,-0.017208,-0.020213,4,1.056986,0.264247,1.375000,1.187500
45,10,79.568550,53.818462,61.680830,0.111111,31.2500,5.014006e+02,7.940182e+02,0.631472,1.716024e+03,38.705675,61.294325,-0.125239,-0.129538,4,1.475606,0.368901,1.312500,1.250000
46,10,80.043884,47.418294,57.763211,0.066667,15.6250,1.173405e+02,4.908423e+02,0.239059,8.554260e+02,19.293625,80.706375,-0.011536,-0.009495,5,1.031258,0.206252,1.050000,1.600000
47,10,82.903630,79.338080,97.412379,0.088235,31.2500,8.504752e+02,9.915634e+02,0.857711,1.842039e+03,46.170327,53.829673,-0.035634,-0.023779,9,6.257389,0.695265,0.972222,5.000000

In [73]:
def norm_with_ref(subjects, feat_mat, ref_mat):
        # This line is redundant, eliminate and substitute application on this cell based on preference.
    channel_cols = [
        col for col in ref_mat.columns if col not in ["Subject"]
    ]

    normdata_list = []

    # Data is normalized per subject
    for subject in subjects:
        data = feat_mat[feat_mat["Subject"] == subject].copy()
        # Baseline normalization
        ref_data = ref_mat[ref_mat["Subject"] == subject].drop(
            "Subject", axis=1
        )
        ref_mean = np.nanmean(ref_data)
        ref_std = np.nanstd(ref_data)
        data[channel_cols] = (data[channel_cols] - ref_mean) / ref_std

        normdata_list.append(data)
    normdata_df = pd.concat(normdata_list, ignore_index=True).fillna(0)

    return normdata_df

norm = norm_with_ref(subjects=subjects, feat_mat=tscene_feat_mat, ref_mat=basal_feat_mat)
norm

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,-0.314758,-0.186063,-0.142181,-0.439523,-0.220956,4.506155e+00,1.953630e+01,-0.439805,2.448265e+01,-0.409250,-0.315232,-0.440291,-0.440294,-0.430837,-0.439176,-0.439988,-0.439490,-0.439607
1,1,-0.310798,-0.226074,-0.112662,-0.439523,-0.269675,-4.401913e-01,9.296058e+00,-0.440191,9.296058e+00,-0.440191,-0.284290,-0.440192,-0.440192,-0.432396,-0.438352,-0.439823,-0.439490,0.000000
2,1,-0.297653,-0.138946,0.045649,-0.439746,-0.172237,-4.401913e-01,1.857427e+01,-0.440191,1.857427e+01,-0.440191,-0.284290,-0.440202,-0.440199,-0.430837,-0.439083,-0.440007,-0.438827,-0.439022
3,1,-0.299220,-0.213265,-0.101966,-0.439746,-0.245315,-4.401913e-01,5.242914e+00,-0.440191,5.242914e+00,-0.440191,-0.284290,-0.440193,-0.440193,-0.426160,-0.439980,-0.440168,-0.438372,-0.438762
4,1,-0.283043,-0.197072,-0.115195,-0.439646,-0.294034,-4.401913e-01,1.254157e+01,-0.440191,1.254157e+01,-0.440191,-0.284290,-0.440190,-0.440189,-0.423042,-0.439931,-0.440168,-0.438845,-0.437902
5,1,-0.313357,-0.219714,-0.155635,-0.439607,-0.220956,2.254318e+00,4.787624e+00,-0.439388,7.482133e+00,-0.387167,-0.337315,-0.440209,-0.440208,-0.423042,-0.439718,-0.440148,-0.438987,-0.438535
6,2,-0.256594,-0.278118,-0.271435,-0.354372,-0.315720,6.759612e-01,7.530351e-01,-0.353390,1.783542e+00,-0.294663,-0.290184,-0.354529,-0.354528,-0.309818,-0.354188,-0.354536,-0.353898,-0.353758
7,2,-0.257888,-0.254118,-0.255015,-0.354270,-0.276893,1.042360e+00,1.291157e+00,-0.353492,2.688064e+00,-0.297504,-0.287344,-0.354521,-0.354521,-0.350819,-0.353051,-0.354048,-0.354132,-0.352993
8,2,-0.260454,-0.253121,-0.268607,-0.354342,-0.286600,2.016759e+00,7.053205e-01,-0.351766,4.873828e+00,-0.268680,-0.316168,-0.354501,-0.354501,-0.348334,-0.352336,-0.354104,-0.353987,-0.352993
9,2,-0.262150,-0.284336,-0.291158,-0.354374,-0.306013,1.182928e+00,7.329508e-02,-0.350081,1.957910e+00,-0.257349,-0.327499,-0.354537,-0.354537,-0.348334,-0.353763,-0.354390,-0.353987,-0.346781
10,2,-0.260239,-0.243254,-0.249733,-0.354298,-0.315720,8.214981e+07,1.241539e+09,-0.354464,1.323689e+09,-0.346835,-0.238012,-0.354543,-0.354543,-0.308576,-0.354280,-0.354539,-0.354034,-0.353640
11,2,-0.256102,-0.217030,-0.195405,-0.354275,-0.315720,2.916286e+00,5.673145e+00,-0.353872,8.943977e+00,-0.310842,-0.274005,-0.354458,-0.354458,-0.350819,-0.353621,-0.354238,-0.351958,-0.352838
12,3,-0.294155,-0.279008,-0.215381,-0.411808,-0.367705,-2.526979e-01,6.698587e+00,-0.411943,6.857864e+00,-0.408871,-0.273414,-0.411790,-0.411789,-0.402058,-0.410859,-0.411815,-0.410356,-0.409425
13,3,-0.295958,-0.296700,-0.291196,-0.411846,-0.367705,1.666281e-01,4.461073e-02,-0.410180,6.232136e-01,-0.332794,-0.349492,-0.412180,-0.412180,-0.402058,-0.410946,-0.411828,-0.410508,-0.408221
14,3,-0.299670,-0.357753,-0.361085,-0.411874,-0.367705,5.207060e-01,3.173931e-02,-0.408997,9.644201e-01,-0.315980,-0.366306,-0.412237,-0.412237,-0.382225,-0.411504,-0.411952,-0.411030,-0.411306
15,3,-0.294868,-0.241254,-0.161928,-0.411767,-0.367705,-6.052002e-02,1.783641e+00,-0.411748,2.135095e+00,-0.392427,-0.289858,-0.412116,-0.412116,-0.382225,-0.411670,-0.411960,-0.411148,-0.411216
16,3,-0.279873,-0.185526,-0.100528,-0.411639,-0.345570,9.869808e-01,3.696925e+00,-0.411492,5.095881e+00,-0.375993,-0.306292,-0.411968,-0.411974,-0.407725,-0.411473,-0.411808,-0.408433,-0.411621
17,3,-0.267414,-0.208928,-0.137168,-0.411566,-0.290232,-2.589664e-02,5.600408e+00,-0.411884,5.986486e+00,-0.403427,-0.278859,-0.411914,-0.411915,-0.404892,-0.410472,-0.411674,-0.410133,-0.405777
18,4,-0.253666,-0.231590,-0.191349,-0.419739,-0.325016,1.157858e+00,3.536076e+00,-0.419302,5.114045e+00,-0.362267,-0.275087,-0.420180,-0.420180,-0.403882,-0.419778,-0.420070,-0.419224,-0.419024
19,4,-0.258528,-0.244574,-0.187855,-0.419634,-0.325016,2.793415e-01,2.466528e+00,-0.419620,3.165980e+00,-0.380542,-0.256811,-0.420235,-0.420238,-0.401853,-0.419755,-0.420067,-0.419160,-0.419024
20,4,-0.253458,-0.228525,-0.157262,-0.419582,-0.325016,2.136457e+00,9.457733e+00,-0.419586,1.201430e+01,-0.378400,-0.258953,-0.420215,-0.420216,-0.363308,-0.419537,-0.420091,-0.419097,-0.418938
21,4,-0.254489,-0.227395,-0.171069,-0.419742,-0.325016,4.731227e+00,3.763335e+00,-0.417613,8.914673e+00,-0.308159,-0.329194,-0.420111,-0.420111,-0.359251,-0.419536,-0.420091,-0.419079,-0.418886
22,4,-0.260368,-0.227180,-0.155966,-0.419664,-0.356715,1.404647e+00,3.627688e+00,-0.419197,5.452446e+00,-0.357075,-0.280279,-0.420111,-0.420109,-0.355193,-0.419544,-0.420093,-0.419049,-0.419139
23,4,-0.262869,-0.255421,-0.210798,-0.419726,-0.356715,3.476813e+00,1.827288e+00,-0.416593,5.724212e+00,-0.291445,-0.345908,-0.420107,-0.420107,-0.332878,-0.419465,-0.420096,-0.419073,-0.419335
24,6,-0.352756,-0.348279,-0.351428,-0.371361,-0.362905,3.738914e-01,3.032743e-01,-0.371087,1.048552e+00,-0.357140,-0.358490,-0.371295,-0.371295,-0.357272,-0.371321,-0.371385,-0.371277,-0.371231
25,6,-0.353688,-0.361986,-0.358664,-0.371356,-0.362905,-3.409836e-01,-2.374641e-01,-0.371325,-2.070611e-01,-0.366365,-0.349266,-0.371336,-0.371336,-0.361615,-0.371333,-0.371385,-0.371280,-0.371224
26,6,-0.353118,-0.356469,-0.356311,-0.371352,-0.362905,-2.106484e-01,-2.528672e-01,-0.371018,-9.212905e-02,-0.355764,-0.359867,-0.371369,-0.371369,-0.363787,-0.371335,-0.371385,-0.371280,-0.371177
27,6,-0.352693,-0.351074,-0.345449,-0.371334,-0.362905,-3.496055e-02,1.109981e-01,-0.371197,4.474241e-01,-0.360234,-0.355396,-0.371386,-0.371385,-0.367587,-0.371318,-0.371382,-0.371202,-0.370986
28,6,-0.352182,-0.351947,-0.348379,-0.371326,-0.358664,-1.054975e-01,2.078215e-01,-0.371262,4.737105e-01,-0.362847,-0.352784,-0.371387,-0.371387,-0.369215,-0.371305,-0.371376,-0.371098,-0.371067
29,6,-0.351844,-0.354949,-0.352260,-0.371336,-0.362905,8.436833e-02,8.133402e-02,-0.371113,5.370889e-01,-0.357770,-0.357861,-0.371381,-0.371382,-0.369487,-0.371251,-0.371367,-0.371086,-0.370993
30,8,-0.297800,-0.302407,-0.290655,-0.370521,-0.325454,1.375950e+00,1.714108e+00,-0.369977,3.460845e+00,-0.326700,-0.318164,-0.370717,-0.370708,-0.363051,-0.366024,-0.370192,-0.369458,-0.368571
31,8,-0.296997,-0.299778,-0.282653,-0.370533,-0.310343,1.303579e-01,2.100250e+00,-0.370591,2.601395e+00,-0.354481,-0.290383,-0.370772,-0.370766,-0.364018,-0.363750,-0.369782,-0.369095,-0.368894
32,8,-0.295493,-0.304765,-0.297547,-0.370565,-0.325454,6.546658e-01,1.436761e+00,-0.370239,2.462214e+00,-0.335781,-0.309083,-0.370904,-0.370894,-0.363051,-0.364878,-0.370049,-0.369125,-0.369164
33,8,-0.293535,-0.321953,-0.315843,-0.370674,-0.340565,4.742947e-01,2.839545e-02,-0.368740,8.929523e-01,-0.305103,-0.339761,-0.370893,-0.370922,-0.363051,-0.364456,-0.369883,-0.369233,-0.369176
34,8,-0.294161,-0.318084,-0.308929,-0.370663,-0.340565,1.144761e-01,7.750385e-01,-0.370378,1.403286e+00,-0.342015,-0.302849,-0.370747,-0.370755,-0.364985,-0.364398,-0.369723,-0.368974,-0.368660
35,8,-0.286547,-0.255897,-0.269906,-0.370537,-0.295232,2.602773e-01,4.382862e+00,-0.370659,5.013927e+00,-0.359453,-0.285411,-0.370661,-0.370632,-0.359182,-0.352843,-0.369292,-0.369579,-0.368059
36,9,-0.159082,-0.206757,-0.176979,-0.286769,-0.265134,-3.690733e-02,3.179921e-01,-0.286332,7.898835e-01,-0.246155,-0.188303,-0.286838,-0.286834,-0.274366,-0.283374,-0.286516,-0.285399,-0.284905
37,9,-0.161319,-0.235926,-0.230220,-0.286839,-0.265134,1.848484e-01,2.091586e-01,-0.285583,7.323502e-01,-0.218980,-0.215479,-0.286894,-0.286892,-0.272972,-0.282167,-0.286381,-0.285166,-0.284569
38,9,-0.162635,-0.242006,-0.228842,-0.286839,-0.265134,-1.142423e-01,4.470449e-01,-0.286580,6.562108e-01,-0.260367,-0.174091,-0.286883,-0.286886,-0.272972,-0.281805,-0.286398,-0.285549,-0.284295
39,9,-0.162308,-0.241437,-0.230557,-0.286835,-0.265134,-1.076709e-01,3.890476e+00,-0.286848,1.815503e+04,-0.281175,-0.153284,-0.286941,-0.286942,-0.267398,-0.280676,-0.286463,-0.285639,-0.285793
40,9,-0.160179,-0.222063,-0.216124,-0.286776,-0.243359,6.802455e-02,2.016025e-01,-0.285896,5.565352e-01,-0.228265,-0.206194,-0.286875,-0.286876,-0.266005,-0.276877,-0.286239,-0.285724,-0.285316
41,9,-0.159084,-0.210775,-0.202115,-0.286698,-0.243359,1.302006e+00,7.816642e-01,-0.284836,2.370578e+00,-0.203586,-0.230873,-0.286725,-0.286733,-0.257643,-0.267822,-0.285999,-0.285929,-0.285793
42,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713519e-02,-9.713450e-02,-0.097135,-9.713425e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135
43,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713522e-02,-9.713501e-02,-0.097135,-9.713474e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135
44,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713485e-02,-9.713500e-02,-0.097135,-9.713439e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135
45,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713498e-02,-9.713475e-02,-0.097135,-9.713402e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135
46,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713529e-02,-9.713499e-02,-0.097135,-9.713470e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135
47,10,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-9.713471e-02,-9.713459e-02,-0.097135,-9.713392e-02,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135,-0.097135

In [74]:
outpath = os.path.join(base_dir, 'Outputs')

norm.to_csv(os.path.join(outpath, rf'biometric_feat_mat_scene_{targetscene}.csv'), index=False)