In [40]:
import customfunctions as ctf
import pandas as pd
import numpy as np
import heartpy as hp
import neurokit2 as nk
import prepro as prep  # Custom functions for preprocessing
import os
import glob
from pathlib import Path
from scipy.ndimage import uniform_filter1d
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Parameters

### Preprocessing parameters

In [41]:
# BVP preprocessing
bvp_prepro_winsz = 10
bvp_prepro_ovlap = 0.02
bvp_fs = 64

# EDA preprocessing
eda_fs = 4
iter_num = 7

### Processing parameters

In [42]:
basalscene = 0
targetscene = 3
# Note, subject 10 does not have scene 2 nor 3 data
subjects = [1, 2, 3, 4, 6, 8, 9]
winsz = 90
ovlap = 0.5
# Outlier removal method, either iqr_outlier, mod_zscore_outlier (both applicable in non-normal data) or winsorization (winsor_outlier)
outliermeth = 'quant_outlier'
# Outlier treatment strategy, either elimination ('elim') or imputation ('impute')
outliertreatment = 'elim'
p_low=0.5
p_high=0.95
# Normalization type, either z-score ('zscore'), mean ('mean'), minmax scaling ('minmax'), robust scaling ('robust')
normtype = 'minmax'
base_dir = Path().resolve()

# Data import function

In [43]:
folderpath = os.path.join(base_dir, "..", "RawData")
folderpath = os.path.abspath(folderpath)


def dataimport(subjects, folderpath, scene):
    bvp_rawdata_list = []
    eda_rawdata_list = []

    for subject in subjects:
        subject_str = f"S{subject}" if subject == 10 else f"S{subject:02d}"
        pattern = os.path.join(
            folderpath,
            f"S{subject}",
            "Empatica",
            f"P300_{subject_str}R0{scene}*",
            "Raw",
        )
        matched_folders = glob.glob(pattern)
        raw_folder = matched_folders[0]
        bvp_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileBVP.csv")).drop(
            "Datetime", axis=1
        )
        eda_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileEDA.csv")).drop(
            "Datetime", axis=1
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_rawdata_list.append(bvp_dataholder)
        eda_rawdata_list.append(eda_dataholder)

    bvp_rawdata_df = pd.concat(bvp_rawdata_list, ignore_index=True)
    eda_rawdata_df = pd.concat(eda_rawdata_list, ignore_index=True)

    return bvp_rawdata_df, eda_rawdata_df


basal_bvp_rawdata, basal_eda_rawdata = dataimport(
    subjects, folderpath, scene=basalscene
)
tscene_bvp_rawdata, tscene_eda_rawdata = dataimport(
    subjects, folderpath, scene=targetscene
)

# Preprocessing function

In [44]:
def preprocess(subjects, bvp_df, eda_df, bvp_fs, eda_fs, winsz, ovlap, iter_num):
    bvp_prepdata_list = []
    eda_prepdata_list = []
    for subject in subjects:
        bvp_dataholder = pd.DataFrame(
            prep.preprocess_bvp(
                sig=bvp_df[bvp_df["Subject"] == subject]["valueBVP"],
                fs=bvp_fs,
                winsz=winsz,
                ovlap=ovlap,
            ),
            columns=["valueBVP"],
        )
        eda_dataholder = pd.DataFrame(
            prep.preprocess_eda(
                sig=eda_df[eda_df["Subject"] == subject]["valueEDA"],
                fs=eda_fs,
                iter_num=iter_num,
                verbose=False,
            )[0],
            columns=["valueEDA"],
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_prepdata_list.append(bvp_dataholder)
        eda_prepdata_list.append(eda_dataholder)

    bvp_prepdata_df = pd.concat(bvp_prepdata_list, ignore_index=True)
    eda_prepdata_df = pd.concat(eda_prepdata_list, ignore_index=True)

    return bvp_prepdata_df, eda_prepdata_df


basal_bvp_prepdata, basal_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=basal_bvp_rawdata,
    eda_df=basal_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

tscene_bvp_prepdata, tscene_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=tscene_bvp_rawdata,
    eda_df=tscene_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

# Processing function

In [45]:
import warnings
def get_bvp_feats(window, smooth_window, fs):
    wd = {}
    wd = hp.peakdetection.detect_peaks(
        window, smooth_window, ma_perc=20, sample_rate=fs
    )
    wd = hp.analysis.calc_rr(wd["peaklist"], sample_rate=fs, working_data=wd)
    wd = hp.peakdetection.check_peaks(
        wd["RR_list"], wd["peaklist"], window[wd["peaklist"]], working_data=wd
    )
    wd = hp.analysis.clean_rr_intervals(working_data=wd, method="quotient-filter")
    rr_list = wd["RR_list_cor"]
    rr_diff = np.diff(rr_list)
    rr_sqdiff = np.power(rr_diff, 2)
    wd, msrs = hp.analysis.calc_ts_measures(
        rr_list, rr_diff, rr_sqdiff, working_data=wd
    )
    wd, msrs = hp.analysis.calc_fd_measures(measures=msrs, working_data=wd)
    bvp_feats = pd.DataFrame([msrs])[
        [
            "bpm",
            "sdnn",
            'rmssd',
            "pnn50",
            "hr_mad",
            "lf",
            "hf",
            "lf/hf",
            "p_total",
            "lf_nu",
            "hf_nu",
        ]
    ]

    return bvp_feats


def get_eda_feats(window, fs):
    signals, info = nk.eda_process(window, fs)
    mean_eda = np.nanmean(window)
    mean_tonic = np.nanmean(signals["EDA_Tonic"])
    scr_peak_count = np.nansum(signals["SCR_Peaks"])
    scr_sum_amp = np.nansum(info["SCR_Amplitude"])
    scr_mean_amp = np.nanmean(info["SCR_Amplitude"])
    scr_mean_risetime = np.nanmean(info["SCR_RiseTime"])
    scr_mean_recoverytime = np.nanmean(info["SCR_RecoveryTime"])

    eda_feats = pd.DataFrame(
        [
            {
                "mean_eda": mean_eda,
                "mean_tonic": mean_tonic,
                "scr_peak_count": scr_peak_count,
                "scr_sum_amp": scr_sum_amp,
                "scr_mean_amp": scr_mean_amp,
                "scr_mean_risetime": scr_mean_risetime,
                "scr_mean_recoverytime": scr_mean_recoverytime,
            }
        ]
    )

    return eda_feats


def process(subjects, bvp_prepdata_df, eda_prepdata_df, bvp_fs, eda_fs, ovlap, winsz):
    feat_mat_list = []
    for subject in subjects:
        # BVP
        bvp_probe = np.array(
            bvp_prepdata_df[bvp_prepdata_df["Subject"] == subject]["valueBVP"]
        )
        bvp_smooth = uniform_filter1d(
            bvp_probe, size=int(0.75 * bvp_fs), mode="nearest"
        )
        bvp_windowed = ctf.timewindowpadded(
            data=bvp_probe, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        smooth_windowed = ctf.timewindowpadded(
            data=bvp_smooth, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        bvp_holder_list = []
        for windnum in range(0,bvp_windowed.shape[0]):
            bvp_feat_row = get_bvp_feats(
                window=bvp_windowed[windnum],
                smooth_window=smooth_windowed[windnum],
                fs=bvp_fs,
            )
            bvp_holder_list.append(bvp_feat_row)
        bvp_holder_df = pd.concat(bvp_holder_list, ignore_index=True)

        # EDA
        eda_probe = np.array(
            eda_prepdata_df[eda_prepdata_df["Subject"] == subject]["valueEDA"]
        )
        eda_windowed = ctf.timewindowpadded(
            data=eda_probe, fs=eda_fs, ovlap=ovlap, winsz=winsz
        )
        eda_holder_list = []
        for windnum in range(0,eda_windowed.shape[0]):
            eda_feat_row = get_eda_feats(window=eda_windowed[windnum], fs=eda_fs)
            eda_holder_list.append(eda_feat_row)
        eda_holder_df = pd.concat(eda_holder_list, ignore_index=True)

        valid_len = min(len(bvp_holder_df), len(eda_holder_df))
        joined_df = pd.concat([bvp_holder_df.iloc[:valid_len], eda_holder_df.iloc[:valid_len]], axis=1)
        joined_df.insert(loc=0, column="Subject", value=[subject] * len(joined_df))
        feat_mat_list.append(joined_df)
        
    feat_mat_df = pd.concat(feat_mat_list, ignore_index=True)
    return feat_mat_df


basal_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=basal_bvp_prepdata,
    eda_prepdata_df=basal_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

tscene_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=tscene_bvp_prepdata,
    eda_prepdata_df=tscene_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

warnings.filterwarnings('ignore')

In [46]:
basal_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,62.466476,60.745158,58.491992,0.136986,39.0625,1.020411e+03,1.069850e+03,0.953789,2.602937e+03,48.817396,51.182604,-0.005557,-0.005470,17,0.133718,0.007866,0.455882,0.750000
1,1,63.840399,74.530595,67.652525,0.126582,46.8750,9.577659e+02,8.816200e+02,1.086370,2.133140e+03,52.069872,47.930128,-0.000625,-0.000620,17,0.109199,0.006825,0.593750,0.950000
2,1,67.908512,101.847943,86.004657,0.121622,62.5000,2.391600e+03,2.279704e+03,1.049084,8.190353e+03,51.197694,48.802306,0.002401,0.002226,18,0.096585,0.005681,1.132353,1.100000
3,1,68.746803,86.251777,62.814230,0.145161,62.5000,8.017548e+02,1.627016e+03,0.492776,2.820222e+03,33.010728,66.989272,0.009608,0.009637,15,0.122990,0.008199,1.050000,1.027778
4,2,71.431793,83.631418,54.698887,0.102041,46.8750,1.013593e+03,8.258658e+02,1.227310,2.730259e+03,55.102794,44.897206,-0.023166,-0.023263,74,0.429396,0.005882,0.414384,0.535714
5,2,74.250000,78.236675,58.271328,0.091837,46.8750,5.973643e+02,8.025838e+02,0.744301,4.640375e+03,42.670461,57.329539,0.001783,0.001801,78,0.461093,0.005911,0.442308,0.632353
6,2,77.111562,85.465727,64.847496,0.102041,62.5000,6.725265e+02,3.094232e+02,2.173484,2.605237e+03,68.488895,31.511105,0.002389,0.001928,26,0.402167,0.015468,0.557692,0.972222
7,2,85.404504,106.789867,111.293637,0.189873,54.6875,2.977515e+03,1.315640e+03,2.263169,6.425113e+03,69.354939,30.645061,-0.000033,0.000183,22,0.376104,0.017096,0.579545,0.966667
8,3,81.923703,56.356810,50.081731,0.128205,31.2500,8.102969e+02,1.374918e+03,0.589342,2.323080e+03,37.080880,62.919120,0.000878,0.000861,35,0.156139,0.004461,0.414286,0.550000
9,3,85.128820,55.584121,51.950588,0.100000,31.2500,5.423301e+02,8.034705e+02,0.674984,1.635130e+03,40.297951,59.702049,-0.000713,-0.000727,36,0.211838,0.005884,0.416667,0.479167
10,3,93.325430,117.438044,118.132124,0.111111,31.2500,1.846046e+03,4.206219e+03,0.438885,6.912307e+03,30.501742,69.498258,-0.001339,-0.001364,40,0.250648,0.006427,0.480769,0.568182
11,3,111.578947,177.126410,157.477152,0.134615,62.5000,1.893640e+03,2.820546e+03,0.671374,4.714186e+03,40.168975,59.831025,0.004001,0.004074,22,0.163186,0.007418,0.545455,0.788462
12,4,72.319055,43.402297,51.212291,0.099010,31.2500,2.755145e+02,1.219170e+03,0.225985,1.533257e+03,18.432952,81.567048,-0.024362,-0.024430,52,0.274197,0.005273,0.600962,0.796875
13,4,73.524171,56.310181,66.786595,0.130000,31.2500,2.510663e+02,1.304987e+03,0.192390,1.722071e+03,16.134811,83.865189,0.001204,0.001249,56,0.286919,0.005124,0.566964,0.615385
14,4,80.610687,95.326976,76.611617,0.183673,78.1250,1.028092e+03,1.630030e+03,0.630720,3.545731e+03,38.677380,61.322620,0.003346,0.002211,4,1.292520,0.323130,0.875000,1.000000
15,4,90.332103,123.084766,66.908275,0.108911,62.5000,9.543475e+07,7.192482e+08,0.132687,5.862628e+13,11.714342,88.285658,0.026970,0.026844,4,1.294144,0.323536,0.875000,2.250000
16,6,101.280154,151.474296,128.331379,0.296296,93.7500,1.374147e+04,5.432828e+03,2.529340,1.917430e+04,71.666092,28.333908,-0.005410,-0.007676,11,0.298678,0.027153,0.795455,1.150000
17,6,110.451999,157.682076,129.592844,0.250000,46.8750,1.007046e+04,8.227901e+03,1.223941,1.829836e+04,55.034771,44.965229,-0.000526,-0.000612,70,0.443108,0.006330,0.432143,0.450000
18,6,89.981001,186.124390,148.918314,0.232877,132.8125,6.670945e+03,2.004851e+03,3.327402,8.675796e+03,76.891447,23.108553,-0.000710,-0.000505,48,0.386324,0.008048,0.494792,0.787500
19,6,84.764681,155.053939,167.685500,0.307692,62.5000,2.325727e+03,1.768756e+04,0.131489,2.001328e+04,11.620919,88.379081,0.029735,0.029562,6,0.963175,0.160529,1.375000,6.937500
20,8,79.240987,60.110790,81.259783,0.197674,31.2500,2.015749e+02,7.827676e+02,0.257516,1.108415e+03,20.478123,79.521877,0.095991,0.096358,9,5.968193,0.663133,1.583333,2.937500
21,8,81.339520,58.331815,62.650060,0.153846,31.2500,9.978687e+02,1.263523e+03,0.789751,2.424465e+03,44.126300,55.873700,0.095762,0.104086,12,7.099256,0.591605,1.479167,2.425000
22,8,82.891099,91.941095,104.947946,0.215909,46.8750,1.960585e+03,1.448522e+03,1.353507,3.550940e+03,57.510214,42.489786,0.066433,0.061250,11,5.894497,0.589450,1.575000,1.892857
23,8,85.367209,106.527469,134.955143,0.272727,70.3125,2.326592e+03,5.027503e+03,0.462773,7.354095e+03,31.636684,68.363316,0.173366,0.175918,7,4.235491,0.605070,1.678571,1.916667
24,9,85.286344,42.777281,41.438176,0.050000,31.2500,1.527877e+02,5.597834e+02,0.272941,8.420358e+02,21.441754,78.558246,0.299966,0.303566,19,3.308965,0.174156,0.763158,1.076923
25,9,87.152161,68.783556,78.576001,0.070175,31.2500,4.149425e+02,1.272867e+03,0.325990,1.805459e+03,24.584671,75.415329,-0.001452,0.003084,16,3.555212,0.222201,1.046875,0.937500
26,9,90.441609,71.883373,79.246157,0.109244,31.2500,3.623925e+02,1.470536e+03,0.246436,3.408685e+03,19.771229,80.228771,-0.479191,-0.472552,17,2.469651,0.145274,0.823529,0.923077
27,9,96.285998,75.346223,81.639690,0.150000,15.6250,3.566522e+02,2.344761e+02,1.521060,6.563660e+02,60.334149,39.665851,-1.989191,-1.987693,6,10.345748,1.724291,0.916667,2.500000

In [47]:
tscene_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,164.365971,132.219350,149.818175,0.303797,85.9375,1296.090196,2059.325665,0.629376,3355.415861,38.626813,61.373187,0.009317,0.009089,20,0.303490,0.015175,0.650000,0.982143
1,1,183.067203,117.753425,163.549030,0.292683,78.1250,665.331751,1607.125991,0.413989,2272.457742,29.278069,70.721931,0.003045,0.003111,26,0.280132,0.010774,0.480769,0.750000
2,1,192.642140,96.986942,118.198472,0.258427,62.5000,114.327087,2356.942880,0.048507,2471.269967,4.626248,95.373752,0.004435,0.004640,16,0.303442,0.018965,0.515625,0.477273
3,1,152.102377,151.589901,139.412634,0.296875,109.3750,985.405568,4644.389513,0.212171,5629.795081,17.503400,82.496600,0.026684,0.026693,5,0.205959,0.041192,0.650000,5.500000
4,2,91.596330,117.800725,146.432282,0.218750,31.2500,757.549784,3482.011957,0.217561,4239.561741,17.868587,82.131413,-0.007472,-0.006858,9,0.306149,0.034017,1.222222,3.000000
5,2,92.530120,129.083685,182.116099,0.245283,39.0625,293.682833,2727.169537,0.107688,3020.852370,9.721853,90.278147,-0.007493,-0.007410,10,0.480404,0.048040,1.475000,2.305556
6,2,103.572519,160.061100,199.674841,0.250000,62.5000,550.521600,5334.521355,0.103200,5885.042955,9.354589,90.645411,-0.003431,-0.004394,27,0.342504,0.013173,0.538462,0.630952
7,2,100.702622,157.484444,177.532013,0.211538,46.8750,1723.003999,5999.462752,0.287193,7722.466751,22.311575,77.688425,-0.023351,-0.023370,20,0.437738,0.021887,0.587500,0.783333
8,3,109.990557,121.862416,115.772710,0.122222,62.5000,3340.782521,6571.043318,0.508410,9911.825839,33.705016,66.294984,-0.021928,-0.018657,6,1.344445,0.224074,1.458333,3.625000
9,3,110.678383,112.241643,115.461179,0.135802,39.0625,1646.535178,4537.992536,0.362833,6184.527714,26.623459,73.376541,-0.013049,-0.012558,15,0.420786,0.028052,0.950000,1.318182
10,3,109.534426,121.270613,142.400373,0.116279,31.2500,1288.992168,3400.934865,0.379011,4689.927033,27.484269,72.515731,-0.050638,-0.051721,8,0.969782,0.121223,2.031250,2.178571
11,3,109.040675,139.240327,165.975173,0.150685,54.6875,1112.296061,3621.034288,0.307176,4733.330349,23.499227,76.500773,0.164744,0.165153,8,1.390860,0.173857,1.906250,2.321429
12,4,87.975831,88.490689,91.301950,0.200000,31.2500,1974.213396,1370.571013,1.440431,3769.162462,59.023637,40.976363,0.045030,0.049790,21,15.478039,0.737049,1.000000,2.343750
13,4,87.876530,87.486689,96.184685,0.258824,54.6875,1301.338460,1836.036667,0.708776,132173.504026,41.478574,58.521426,0.041453,0.046720,24,19.444587,0.810191,1.125000,0.954545
14,4,87.249121,67.915237,88.571192,0.289157,46.8750,282.178714,1936.602094,0.145708,2299.718177,12.717737,87.282263,-0.029828,-0.025208,24,22.172565,0.923857,0.864583,1.055556
15,4,83.373191,67.239040,70.107954,0.220588,31.2500,2259.406429,1955.378562,1.155483,4214.784991,53.606683,46.393317,-0.354059,-0.397313,21,17.382986,0.869149,0.775000,2.357143
16,6,80.222841,110.649813,143.335461,0.322034,78.1250,1576.167519,2230.416161,0.706670,3806.583680,41.406354,58.593646,-0.035617,-0.035742,10,3.130939,0.313094,2.075000,1.437500
17,6,79.723183,122.174001,160.654318,0.358491,78.1250,3497.333911,7363.886094,0.474930,10861.220005,32.200194,67.799806,0.088876,0.096218,10,4.558591,0.455859,1.600000,1.305556
18,6,81.126761,128.139820,142.379591,0.406780,62.5000,6090.462005,5156.589216,1.181103,11247.051221,54.151634,45.848366,-0.016810,-0.018401,8,4.080164,0.510021,1.312500,1.656250
19,6,80.264026,114.325972,144.840102,0.375000,62.5000,1248.386365,3450.264486,0.361823,4698.650851,26.569039,73.430961,0.121771,0.136777,7,1.818134,0.259733,1.714286,1.300000
20,8,83.793103,100.718092,125.377847,0.312500,62.5000,758.079938,1502.536185,0.504534,2911.263665,33.534218,66.465782,0.210852,0.219476,15,11.580978,0.772065,0.900000,1.416667
21,8,86.391693,99.535915,124.134585,0.311688,62.5000,3443.527905,1732.517420,1.987586,5253.707484,66.528164,33.471836,0.068839,0.056050,24,22.590521,0.982197,0.891304,0.977273
22,8,91.061093,144.217659,175.125994,0.327586,78.1250,3766.392513,4549.169974,0.827930,8315.562488,45.293298,54.706702,-0.807948,-0.791783,20,25.295283,1.264764,0.887500,1.057692
23,8,103.924222,164.469362,172.184308,0.333333,132.8125,4452.245429,8236.830047,0.540529,12689.075476,35.087233,64.912767,-2.138396,-2.147002,26,39.064773,1.502491,0.903846,1.403846
24,9,105.329154,100.986314,106.757396,0.250000,46.8750,1569.146443,2609.357773,0.601354,5166.144006,37.552827,62.447173,-0.005573,0.000090,17,11.606529,0.682737,1.000000,2.100000
25,9,105.032823,100.421961,92.144823,0.232323,46.8750,1175.065031,2147.492383,0.547180,3493.250428,35.366282,64.633718,-0.031275,-0.034193,21,2.229423,0.106163,0.726190,1.053571
26,9,100.462281,58.420082,58.972936,0.127451,31.2500,457.471387,375.797163,1.217336,946.326271,54.900834,45.099166,-0.013444,-0.012196,15,3.028934,0.201929,1.083333,1.425000
27,9,101.386139,66.629908,87.562845,0.151899,31.2500,423.134001,311.911505,1.356583,735.045506,57.565688,42.434312,2.100410,2.101893,2,13.787494,6.893747,3.625000,1.500000

In [48]:
def remove_outliers_iqr(col, ref, p_low=0.25, p_high=0.75, treatment="elim"):
    q1 = ref.quantile(p_low)
    q3 = ref.quantile(p_high)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    if treatment == "impute":
        return col.clip(lower=lower, upper=upper)
    else:
        return col[(col >= lower) & (col <= upper)]


def remove_outliers_zscore(col, ref):
    mean = ref.mean()
    std = ref.std()
    return col[np.abs((col - mean) / std) < 3]


def remove_outliers_winsor(col, p_low=0.05, p_high=0.95, treatment="impute"):
    lower = col.quantile(p_low)
    upper = col.quantile(p_high)
    return col.clip(lower=lower, upper=upper)

channel_cols = [col for col in basal_feat_mat.columns if col not in ["Subject"]]

## Baseline outlier treatment
basal_outlier_treated = basal_feat_mat.copy()

if outliermeth == 'winsor_outlier':
    basal_outlier_treated[channel_cols] = basal_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_winsor(s, p_low=0.05, p_high=0.95)
    )
elif outliermeth == 'zscore_outlier':
    basal_outlier_treated[channel_cols] = basal_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_zscore(s, s)
    )
elif outliermeth == 'quant_outlier':
    basal_outlier_treated[channel_cols] = basal_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_iqr(s, s, p_low=0.05, p_high=0.95, treatment=outliertreatment)
    )


## Target scene outlier treatment
tscene_outlier_treated = tscene_feat_mat.copy()

if outliermeth == 'winsor_outlier':
    tscene_outlier_treated[channel_cols] = tscene_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_winsor(s, p_low=0.1, p_high=0.9)
    )
elif outliermeth == 'zscore_outlier':
    tscene_outlier_treated[channel_cols] = tscene_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_zscore(s, basal_feat_mat[s.name])
    )
elif outliermeth == 'quant_outlier':
    tscene_outlier_treated[channel_cols] = tscene_feat_mat[channel_cols].apply(
        lambda s: remove_outliers_iqr(s, basal_feat_mat[s.name], p_low=0.05, p_high=0.95, treatment=outliertreatment)
    )

basal_outlier_treated.dropna(inplace=True)
tscene_outlier_treated.dropna(inplace=True)

In [49]:
tscene_outlier_treated

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,164.365971,132.219350,149.818175,0.303797,85.9375,1296.090196,2059.325665,0.629376,3355.415861,38.626813,61.373187,0.009317,0.009089,20,0.303490,0.015175,0.650000,0.982143
3,1,152.102377,151.589901,139.412634,0.296875,109.3750,985.405568,4644.389513,0.212171,5629.795081,17.503400,82.496600,0.026684,0.026693,5,0.205959,0.041192,0.650000,5.500000
4,2,91.596330,117.800725,146.432282,0.218750,31.2500,757.549784,3482.011957,0.217561,4239.561741,17.868587,82.131413,-0.007472,-0.006858,9,0.306149,0.034017,1.222222,3.000000
5,2,92.530120,129.083685,182.116099,0.245283,39.0625,293.682833,2727.169537,0.107688,3020.852370,9.721853,90.278147,-0.007493,-0.007410,10,0.480404,0.048040,1.475000,2.305556
6,2,103.572519,160.061100,199.674841,0.250000,62.5000,550.521600,5334.521355,0.103200,5885.042955,9.354589,90.645411,-0.003431,-0.004394,27,0.342504,0.013173,0.538462,0.630952
7,2,100.702622,157.484444,177.532013,0.211538,46.8750,1723.003999,5999.462752,0.287193,7722.466751,22.311575,77.688425,-0.023351,-0.023370,20,0.437738,0.021887,0.587500,0.783333
8,3,109.990557,121.862416,115.772710,0.122222,62.5000,3340.782521,6571.043318,0.508410,9911.825839,33.705016,66.294984,-0.021928,-0.018657,6,1.344445,0.224074,1.458333,3.625000
9,3,110.678383,112.241643,115.461179,0.135802,39.0625,1646.535178,4537.992536,0.362833,6184.527714,26.623459,73.376541,-0.013049,-0.012558,15,0.420786,0.028052,0.950000,1.318182
10,3,109.534426,121.270613,142.400373,0.116279,31.2500,1288.992168,3400.934865,0.379011,4689.927033,27.484269,72.515731,-0.050638,-0.051721,8,0.969782,0.121223,2.031250,2.178571
11,3,109.040675,139.240327,165.975173,0.150685,54.6875,1112.296061,3621.034288,0.307176,4733.330349,23.499227,76.500773,0.164744,0.165153,8,1.390860,0.173857,1.906250,2.321429
12,4,87.975831,88.490689,91.301950,0.200000,31.2500,1974.213396,1370.571013,1.440431,3769.162462,59.023637,40.976363,0.045030,0.049790,21,15.478039,0.737049,1.000000,2.343750
16,6,80.222841,110.649813,143.335461,0.322034,78.1250,1576.167519,2230.416161,0.706670,3806.583680,41.406354,58.593646,-0.035617,-0.035742,10,3.130939,0.313094,2.075000,1.437500
17,6,79.723183,122.174001,160.654318,0.358491,78.1250,3497.333911,7363.886094,0.474930,10861.220005,32.200194,67.799806,0.088876,0.096218,10,4.558591,0.455859,1.600000,1.305556
18,6,81.126761,128.139820,142.379591,0.406780,62.5000,6090.462005,5156.589216,1.181103,11247.051221,54.151634,45.848366,-0.016810,-0.018401,8,4.080164,0.510021,1.312500,1.656250
19,6,80.264026,114.325972,144.840102,0.375000,62.5000,1248.386365,3450.264486,0.361823,4698.650851,26.569039,73.430961,0.121771,0.136777,7,1.818134,0.259733,1.714286,1.300000
20,8,83.793103,100.718092,125.377847,0.312500,62.5000,758.079938,1502.536185,0.504534,2911.263665,33.534218,66.465782,0.210852,0.219476,15,11.580978,0.772065,0.900000,1.416667
24,9,105.329154,100.986314,106.757396,0.250000,46.8750,1569.146443,2609.357773,0.601354,5166.144006,37.552827,62.447173,-0.005573,0.000090,17,11.606529,0.682737,1.000000,2.100000
25,9,105.032823,100.421961,92.144823,0.232323,46.8750,1175.065031,2147.492383,0.547180,3493.250428,35.366282,64.633718,-0.031275,-0.034193,21,2.229423,0.106163,0.726190,1.053571
26,9,100.462281,58.420082,58.972936,0.127451,31.2500,457.471387,375.797163,1.217336,946.326271,54.900834,45.099166,-0.013444,-0.012196,15,3.028934,0.201929,1.083333,1.425000

In [50]:
list(tscene_outlier_treated['Subject'].unique())

[1, 2, 3, 4, 6, 8, 9]

In [51]:
def norm_with_ref(
    subjects,
    feat_mat,
    ref_mat,
    normtype=str,
):
    channel_cols = [col for col in ref_mat.columns if col not in ["Subject"]]

    normdata_list = []

    # Data is normalized per subject 
    for subject in subjects:
        data = feat_mat[feat_mat["Subject"] == subject].copy()

        ref_data = ref_mat[ref_mat["Subject"] == subject].copy().drop("Subject", axis=1)


        if normtype == "zscore":
            scaler = StandardScaler()
            scaler.fit(ref_data[channel_cols])
            data[channel_cols] = scaler.transform(data[channel_cols])
        elif normtype == "minmax":
            scaler = MinMaxScaler()
            scaler.fit(ref_data[channel_cols])
            data[channel_cols] = scaler.transform(data[channel_cols])
        normdata_list.append(data.dropna())
    normdata_df = pd.concat(normdata_list, ignore_index=True)

    return normdata_df

subjects = tscene_outlier_treated['Subject'].unique()
norm = norm_with_ref(
    subjects=subjects,
    feat_mat=tscene_outlier_treated,
    ref_mat=basal_outlier_treated,
    normtype=normtype,
)
norm

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,16.225190,1.738914,3.319423,7.739100,2.000000,0.310933,0.842371,0.230123,0.201789,0.294666,0.705334,0.980858,0.963736,1.666667,5.572079,3.770316,0.286957,0.663265
1,1,14.272490,2.210185,2.941214,7.445023,3.000000,0.115515,2.691375,-0.472722,0.577271,-0.813642,1.813642,2.126065,2.129026,-3.333333,2.945486,14.103483,0.286957,13.571429
2,2,1.443137,1.385626,1.620882,1.294549,-1.000000,0.067301,3.152987,-0.346798,0.427848,-0.929449,1.929449,0.614132,0.651217,-0.232143,-0.823109,2.508978,4.891193,5.645455
3,2,1.509967,1.780782,2.251396,1.565193,-0.500000,-0.127589,2.402809,-0.419137,0.108803,-1.234748,2.234748,0.613287,0.629306,-0.214286,1.227216,3.759595,6.421678,4.054545
4,2,2.300250,2.865684,2.561650,1.613307,1.000000,-0.019681,4.994051,-0.422092,0.858616,-1.248511,2.248511,0.772247,0.749015,0.089286,-0.395353,0.650205,0.751251,0.218182
5,2,2.094857,2.775443,2.170398,1.220989,0.000000,0.472928,5.654885,-0.300954,1.339632,-0.762949,1.762949,-0.007223,-0.004275,-0.035714,0.725198,1.427275,1.048162,0.567273
6,3,0.946438,0.545311,0.611674,0.641975,1.000000,2.070918,1.694975,0.294472,1.568395,0.326991,0.673009,-3.855830,-3.179704,-0.888889,12.573426,74.282848,7.959571,10.170984
7,3,0.969632,0.466155,0.608773,1.034294,0.250000,0.817137,1.097502,-0.322117,0.862089,-0.395896,1.395896,-2.192904,-2.058288,-0.388889,2.800215,7.979604,4.084158,2.712671
8,3,0.931057,0.540441,0.859614,0.470284,0.000000,0.552547,0.763343,-0.253596,0.578870,-0.308025,1.308025,-9.232387,-9.259375,-0.777778,8.609130,39.493953,12.327351,5.494449
9,3,0.914407,0.688289,1.079128,1.464231,0.750000,0.421788,0.828026,-0.557853,0.587094,-0.714819,1.714819,31.103080,30.618416,-0.777778,13.064536,57.297327,11.374381,5.956329
10,4,1.888262,0.868342,1.578375,1.192840,0.000000,2.217620,0.368498,2.847266,1.111023,1.902570,-0.902570,2.504364,2.785886,0.326923,14.930270,2.301607,1.405797,4.493750
11,6,-0.476682,-1.178193,0.728816,1.405831,0.363636,-0.720566,0.036247,-0.245914,-0.463801,-0.623536,1.623536,-6.184308,-3.913455,-0.016949,19.609819,14.732396,4.521895,1.410714
12,6,-0.501090,-0.845605,1.570071,1.980679,0.363636,-0.448851,0.861159,-0.356085,0.208165,-1.044742,2.044742,19.303825,14.487243,-0.016949,29.494504,21.588729,3.214477,1.222222
13,6,-0.432526,-0.673432,0.682385,2.742102,0.181818,-0.082099,0.506462,-0.020365,0.244916,-0.040406,1.040406,-2.333958,-1.495460,-0.050847,26.182002,24.189841,2.423146,1.723214
14,6,-0.474670,-1.072099,0.801903,2.241000,0.181818,-0.766924,0.232268,-0.409856,-0.378830,-1.302382,2.302382,26.038608,20.142819,-0.067797,10.520307,12.169746,3.529044,1.214286
15,8,0.743054,0.879463,0.867543,1.334559,0.800000,0.261883,0.169567,0.225383,0.288655,0.352562,0.647438,1.350552,1.379858,1.600000,2.564975,2.478398,-2.904478,-0.455840
16,9,3.887833,1.999892,1.727657,3.375887,15.625000,5.402758,2.250418,4.461305,1.684729,3.694154,-2.694154,0.607859,0.608982,0.333333,8.416735,6.986654,0.834783,7.650000
17,9,3.830351,1.980502,1.341163,3.077513,15.625000,3.899518,1.743293,3.780347,1.032948,3.239896,-2.239896,0.574872,0.564809,1.666667,-0.221294,-0.508411,-0.130297,0.848214
18,9,2.943774,0.537441,0.463785,1.307329,0.000000,1.162228,-0.202015,12.204182,0.040633,7.298230,-6.298230,0.597757,0.593152,-0.333333,0.515202,0.736480,1.128502,3.262500

In [52]:
outpath = os.path.join(base_dir, 'Outputs', f'outlier_{outliertreatment}', outliermeth)
basal_outlier_treated.to_csv(os.path.join(outpath,'non-normalized',rf'biometric_feat_mat_scene_{basalscene}_nonnorm.csv'), index=False)
tscene_outlier_treated.to_csv(os.path.join(outpath,'non-normalized',rf'biometric_feat_mat_scene_{targetscene}_nonnorm.csv'), index=False)
norm.to_csv(os.path.join(outpath, rf'biometric_feat_mat_scene_{targetscene}_{normtype}.csv'), index=False)

In [58]:
x_labels = ["Baseline"] + [f"Scene {i+1}" for i in range(5)]
x_labels

['Baseline', 'Scene 1', 'Scene 2', 'Scene 3', 'Scene 4', 'Scene 5']

In [59]:
x_labels

['Baseline', 'Scene 1', 'Scene 2', 'Scene 3', 'Scene 4', 'Scene 5']

In [60]:
print(x_labels)

['Baseline', 'Scene 1', 'Scene 2', 'Scene 3', 'Scene 4', 'Scene 5']