In [137]:
import customfunctions as ctf
import pandas as pd
import numpy as np
import heartpy as hp
import neurokit2 as nk
import prepro as prep  # Custom functions for preprocessing
import os
import glob
from pathlib import Path
from scipy.ndimage import uniform_filter1d
from sklearn.preprocessing import MinMaxScaler, RobustScaler

# Parameters

### Preprocessing parameters

In [138]:
# BVP preprocessing
bvp_prepro_winsz = 10
bvp_prepro_ovlap = 0.02
bvp_fs = 64

# EDA preprocessing
eda_fs = 4
iter_num = 7

### Processing parameters

In [139]:
basalscene = 0
targetscene = 4
# Note, subject 10 does not have scene 2 nor 3 data
subjects = [1, 2, 3, 4, 6, 8, 9]
winsz = 90
ovlap = 0.5
# Outlier removal method, either iqr_outlier, mod_zscore_outlier (both applicable in non-normal data) or winsorization (winsor_outlier)
outliermeth = 'winsor_outlier'
# Outlier treatment strategy, either elimination ('elim') or imputation ('impute')
outliertreatment = 'impute'
p_low=0.5
p_high=0.95
# Normalization type, either z-score ('zscore'), mean ('mean'), minmax scaling ('minmax'), robust scaling ('robust')
normtype = 'zscore'
base_dir = Path().resolve()

# Data import function

In [140]:
folderpath = os.path.join(base_dir, "..", "RawData")
folderpath = os.path.abspath(folderpath)


def dataimport(subjects, folderpath, scene):
    bvp_rawdata_list = []
    eda_rawdata_list = []

    for subject in subjects:
        subject_str = f"S{subject}" if subject == 10 else f"S{subject:02d}"
        pattern = os.path.join(
            folderpath,
            f"S{subject}",
            "Empatica",
            f"P300_{subject_str}R0{scene}*",
            "Raw",
        )
        matched_folders = glob.glob(pattern)
        raw_folder = matched_folders[0]
        bvp_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileBVP.csv")).drop(
            "Datetime", axis=1
        )
        eda_dataholder = pd.read_csv(os.path.join(raw_folder, r"fileEDA.csv")).drop(
            "Datetime", axis=1
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_rawdata_list.append(bvp_dataholder)
        eda_rawdata_list.append(eda_dataholder)

    bvp_rawdata_df = pd.concat(bvp_rawdata_list, ignore_index=True)
    eda_rawdata_df = pd.concat(eda_rawdata_list, ignore_index=True)

    return bvp_rawdata_df, eda_rawdata_df


basal_bvp_rawdata, basal_eda_rawdata = dataimport(
    subjects, folderpath, scene=basalscene
)
tscene_bvp_rawdata, tscene_eda_rawdata = dataimport(
    subjects, folderpath, scene=targetscene
)

# Preprocessing function

In [141]:
def preprocess(subjects, bvp_df, eda_df, bvp_fs, eda_fs, winsz, ovlap, iter_num):
    bvp_prepdata_list = []
    eda_prepdata_list = []
    for subject in subjects:
        bvp_dataholder = pd.DataFrame(
            prep.preprocess_bvp(
                sig=bvp_df[bvp_df["Subject"] == subject]["valueBVP"],
                fs=bvp_fs,
                winsz=winsz,
                ovlap=ovlap,
            ),
            columns=["valueBVP"],
        )
        eda_dataholder = pd.DataFrame(
            prep.preprocess_eda(
                sig=eda_df[eda_df["Subject"] == subject]["valueEDA"],
                fs=eda_fs,
                iter_num=iter_num,
                verbose=False,
            )[0],
            columns=["valueEDA"],
        )

        bvp_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(bvp_dataholder)
        )
        eda_dataholder.insert(
            loc=0, column="Subject", value=[subject] * len(eda_dataholder)
        )

        bvp_prepdata_list.append(bvp_dataholder)
        eda_prepdata_list.append(eda_dataholder)

    bvp_prepdata_df = pd.concat(bvp_prepdata_list, ignore_index=True)
    eda_prepdata_df = pd.concat(eda_prepdata_list, ignore_index=True)

    return bvp_prepdata_df, eda_prepdata_df


basal_bvp_prepdata, basal_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=basal_bvp_rawdata,
    eda_df=basal_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

tscene_bvp_prepdata, tscene_eda_prepdata = preprocess(
    subjects=subjects,
    bvp_df=tscene_bvp_rawdata,
    eda_df=tscene_eda_rawdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    winsz=bvp_prepro_winsz,
    ovlap=bvp_prepro_ovlap,
    iter_num=iter_num,
)

# Processing function

In [142]:
import warnings
def get_bvp_feats(window, smooth_window, fs):
    wd = {}
    wd = hp.peakdetection.detect_peaks(
        window, smooth_window, ma_perc=20, sample_rate=fs
    )
    wd = hp.analysis.calc_rr(wd["peaklist"], sample_rate=fs, working_data=wd)
    wd = hp.peakdetection.check_peaks(
        wd["RR_list"], wd["peaklist"], window[wd["peaklist"]], working_data=wd
    )
    wd = hp.analysis.clean_rr_intervals(working_data=wd, method="quotient-filter")
    rr_list = wd["RR_list_cor"]
    rr_diff = np.diff(rr_list)
    rr_sqdiff = np.power(rr_diff, 2)
    wd, msrs = hp.analysis.calc_ts_measures(
        rr_list, rr_diff, rr_sqdiff, working_data=wd
    )
    wd, msrs = hp.analysis.calc_fd_measures(measures=msrs, working_data=wd)
    bvp_feats = pd.DataFrame([msrs])[
        [
            "bpm",
            "sdnn",
            'rmssd',
            "pnn50",
            "hr_mad",
            "lf",
            "hf",
            "lf/hf",
            "p_total",
            "lf_nu",
            "hf_nu",
        ]
    ]

    return bvp_feats


def get_eda_feats(window, fs):
    signals, info = nk.eda_process(window, fs)
    mean_eda = np.nanmean(window)
    mean_tonic = np.nanmean(signals["EDA_Tonic"])
    scr_peak_count = np.nansum(signals["SCR_Peaks"])
    scr_sum_amp = np.nansum(info["SCR_Amplitude"])
    scr_mean_amp = np.nanmean(info["SCR_Amplitude"])
    scr_mean_risetime = np.nanmean(info["SCR_RiseTime"])
    scr_mean_recoverytime = np.nanmean(info["SCR_RecoveryTime"])

    eda_feats = pd.DataFrame(
        [
            {
                "mean_eda": mean_eda,
                "mean_tonic": mean_tonic,
                "scr_peak_count": scr_peak_count,
                "scr_sum_amp": scr_sum_amp,
                "scr_mean_amp": scr_mean_amp,
                "scr_mean_risetime": scr_mean_risetime,
                "scr_mean_recoverytime": scr_mean_recoverytime,
            }
        ]
    )

    return eda_feats


def process(subjects, bvp_prepdata_df, eda_prepdata_df, bvp_fs, eda_fs, ovlap, winsz):
    feat_mat_list = []
    for subject in subjects:
        # BVP
        bvp_probe = np.array(
            bvp_prepdata_df[bvp_prepdata_df["Subject"] == subject]["valueBVP"]
        )
        bvp_smooth = uniform_filter1d(
            bvp_probe, size=int(0.75 * bvp_fs), mode="nearest"
        )
        bvp_windowed = ctf.timewindowpadded(
            data=bvp_probe, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        smooth_windowed = ctf.timewindowpadded(
            data=bvp_smooth, fs=bvp_fs, ovlap=ovlap, winsz=winsz
        )
        bvp_holder_list = []
        for windnum in range(0,bvp_windowed.shape[0]):
            bvp_feat_row = get_bvp_feats(
                window=bvp_windowed[windnum],
                smooth_window=smooth_windowed[windnum],
                fs=bvp_fs,
            )
            bvp_holder_list.append(bvp_feat_row)
        bvp_holder_df = pd.concat(bvp_holder_list, ignore_index=True)

        # EDA
        eda_probe = np.array(
            eda_prepdata_df[eda_prepdata_df["Subject"] == subject]["valueEDA"]
        )
        eda_windowed = ctf.timewindowpadded(
            data=eda_probe, fs=eda_fs, ovlap=ovlap, winsz=winsz
        )
        eda_holder_list = []
        for windnum in range(0,eda_windowed.shape[0]):
            eda_feat_row = get_eda_feats(window=eda_windowed[windnum], fs=eda_fs)
            eda_holder_list.append(eda_feat_row)
        eda_holder_df = pd.concat(eda_holder_list, ignore_index=True)

        valid_len = min(len(bvp_holder_df), len(eda_holder_df))
        joined_df = pd.concat([bvp_holder_df.iloc[:valid_len], eda_holder_df.iloc[:valid_len]], axis=1)
        joined_df.insert(loc=0, column="Subject", value=[subject] * len(joined_df))
        feat_mat_list.append(joined_df)
        
    feat_mat_df = pd.concat(feat_mat_list, ignore_index=True)
    return feat_mat_df


basal_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=basal_bvp_prepdata,
    eda_prepdata_df=basal_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

tscene_feat_mat = process(
    subjects=subjects,
    bvp_prepdata_df=tscene_bvp_prepdata,
    eda_prepdata_df=tscene_eda_prepdata,
    bvp_fs=bvp_fs,
    eda_fs=eda_fs,
    ovlap=ovlap,
    winsz=winsz,
)

warnings.filterwarnings('ignore')

In [143]:
basal_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,62.466476,60.745158,58.491992,0.136986,39.0625,1.020411e+03,1.069850e+03,0.953789,2.602937e+03,48.817396,51.182604,-0.005557,-0.005470,17,0.133718,0.007866,0.455882,0.750000
1,1,63.840399,74.530595,67.652525,0.126582,46.8750,9.577659e+02,8.816200e+02,1.086370,2.133140e+03,52.069872,47.930128,-0.000625,-0.000620,17,0.109199,0.006825,0.593750,0.950000
2,1,67.908512,101.847943,86.004657,0.121622,62.5000,2.391600e+03,2.279704e+03,1.049084,8.190353e+03,51.197694,48.802306,0.002401,0.002226,18,0.096585,0.005681,1.132353,1.100000
3,1,68.746803,86.251777,62.814230,0.145161,62.5000,8.017548e+02,1.627016e+03,0.492776,2.820222e+03,33.010728,66.989272,0.009608,0.009637,15,0.122990,0.008199,1.050000,1.027778
4,2,71.431793,83.631418,54.698887,0.102041,46.8750,1.013593e+03,8.258658e+02,1.227310,2.730259e+03,55.102794,44.897206,-0.023166,-0.023263,74,0.429396,0.005882,0.414384,0.535714
5,2,74.250000,78.236675,58.271328,0.091837,46.8750,5.973643e+02,8.025838e+02,0.744301,4.640375e+03,42.670461,57.329539,0.001783,0.001801,78,0.461093,0.005911,0.442308,0.632353
6,2,77.111562,85.465727,64.847496,0.102041,62.5000,6.725265e+02,3.094232e+02,2.173484,2.605237e+03,68.488895,31.511105,0.002389,0.001928,26,0.402167,0.015468,0.557692,0.972222
7,2,85.404504,106.789867,111.293637,0.189873,54.6875,2.977515e+03,1.315640e+03,2.263169,6.425113e+03,69.354939,30.645061,-0.000033,0.000183,22,0.376104,0.017096,0.579545,0.966667
8,3,81.923703,56.356810,50.081731,0.128205,31.2500,8.102969e+02,1.374918e+03,0.589342,2.323080e+03,37.080880,62.919120,0.000878,0.000861,35,0.156139,0.004461,0.414286,0.550000
9,3,85.128820,55.584121,51.950588,0.100000,31.2500,5.423301e+02,8.034705e+02,0.674984,1.635130e+03,40.297951,59.702049,-0.000713,-0.000727,36,0.211838,0.005884,0.416667,0.479167
10,3,93.325430,117.438044,118.132124,0.111111,31.2500,1.846046e+03,4.206219e+03,0.438885,6.912307e+03,30.501742,69.498258,-0.001339,-0.001364,40,0.250648,0.006427,0.480769,0.568182
11,3,111.578947,177.126410,157.477152,0.134615,62.5000,1.893640e+03,2.820546e+03,0.671374,4.714186e+03,40.168975,59.831025,0.004001,0.004074,22,0.163186,0.007418,0.545455,0.788462
12,4,72.319055,43.402297,51.212291,0.099010,31.2500,2.755145e+02,1.219170e+03,0.225985,1.533257e+03,18.432952,81.567048,-0.024362,-0.024430,52,0.274197,0.005273,0.600962,0.796875
13,4,73.524171,56.310181,66.786595,0.130000,31.2500,2.510663e+02,1.304987e+03,0.192390,1.722071e+03,16.134811,83.865189,0.001204,0.001249,56,0.286919,0.005124,0.566964,0.615385
14,4,80.610687,95.326976,76.611617,0.183673,78.1250,1.028092e+03,1.630030e+03,0.630720,3.545731e+03,38.677380,61.322620,0.003346,0.002211,4,1.292520,0.323130,0.875000,1.000000
15,4,90.332103,123.084766,66.908275,0.108911,62.5000,9.543475e+07,7.192482e+08,0.132687,5.862628e+13,11.714342,88.285658,0.026970,0.026844,4,1.294144,0.323536,0.875000,2.250000
16,6,101.280154,151.474296,128.331379,0.296296,93.7500,1.374147e+04,5.432828e+03,2.529340,1.917430e+04,71.666092,28.333908,-0.005410,-0.007676,11,0.298678,0.027153,0.795455,1.150000
17,6,110.451999,157.682076,129.592844,0.250000,46.8750,1.007046e+04,8.227901e+03,1.223941,1.829836e+04,55.034771,44.965229,-0.000526,-0.000612,70,0.443108,0.006330,0.432143,0.450000
18,6,89.981001,186.124390,148.918314,0.232877,132.8125,6.670945e+03,2.004851e+03,3.327402,8.675796e+03,76.891447,23.108553,-0.000710,-0.000505,48,0.386324,0.008048,0.494792,0.787500
19,6,84.764681,155.053939,167.685500,0.307692,62.5000,2.325727e+03,1.768756e+04,0.131489,2.001328e+04,11.620919,88.379081,0.029735,0.029562,6,0.963175,0.160529,1.375000,6.937500
20,8,79.240987,60.110790,81.259783,0.197674,31.2500,2.015749e+02,7.827676e+02,0.257516,1.108415e+03,20.478123,79.521877,0.095991,0.096358,9,5.968193,0.663133,1.583333,2.937500
21,8,81.339520,58.331815,62.650060,0.153846,31.2500,9.978687e+02,1.263523e+03,0.789751,2.424465e+03,44.126300,55.873700,0.095762,0.104086,12,7.099256,0.591605,1.479167,2.425000
22,8,82.891099,91.941095,104.947946,0.215909,46.8750,1.960585e+03,1.448522e+03,1.353507,3.550940e+03,57.510214,42.489786,0.066433,0.061250,11,5.894497,0.589450,1.575000,1.892857
23,8,85.367209,106.527469,134.955143,0.272727,70.3125,2.326592e+03,5.027503e+03,0.462773,7.354095e+03,31.636684,68.363316,0.173366,0.175918,7,4.235491,0.605070,1.678571,1.916667
24,9,85.286344,42.777281,41.438176,0.050000,31.2500,1.527877e+02,5.597834e+02,0.272941,8.420358e+02,21.441754,78.558246,0.299966,0.303566,19,3.308965,0.174156,0.763158,1.076923
25,9,87.152161,68.783556,78.576001,0.070175,31.2500,4.149425e+02,1.272867e+03,0.325990,1.805459e+03,24.584671,75.415329,-0.001452,0.003084,16,3.555212,0.222201,1.046875,0.937500
26,9,90.441609,71.883373,79.246157,0.109244,31.2500,3.623925e+02,1.470536e+03,0.246436,3.408685e+03,19.771229,80.228771,-0.479191,-0.472552,17,2.469651,0.145274,0.823529,0.923077
27,9,96.285998,75.346223,81.639690,0.150000,15.6250,3.566522e+02,2.344761e+02,1.521060,6.563660e+02,60.334149,39.665851,-1.989191,-1.987693,6,10.345748,1.724291,0.916667,2.500000

In [144]:
tscene_feat_mat

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,81.836066,152.535356,183.818015,0.400000,132.8125,555.034557,8813.351106,0.062977,9.368386e+03,5.924549,94.075451,-0.045856,-0.046815,8,1.216692,0.173813,0.500000,0.500000
1,1,82.781641,162.364117,198.894241,0.300000,125.0000,2637.181814,21458.035604,0.122899,2.409522e+04,10.944835,89.055165,0.002018,0.001967,9,0.780578,0.086731,0.916667,2.687500
2,1,95.506003,162.295716,209.194185,0.321429,109.3750,328.932239,10734.888424,0.030641,1.106382e+04,2.973044,97.026956,-0.000685,-0.000626,15,0.194791,0.012986,0.916667,1.386364
3,1,83.666416,150.505660,178.519105,0.357143,125.0000,6156.922797,2618.510736,2.351307,8.775434e+03,70.160896,29.839104,-0.007803,-0.007733,13,0.377604,0.029046,0.942308,1.700000
4,2,78.580079,75.979394,76.874659,0.185567,46.8750,12298.684488,102159.925499,0.120387,4.864561e+08,10.745093,89.254907,0.028943,0.029459,3,1.203188,0.401063,0.333333,1.250000
5,2,75.445068,73.168328,68.916007,0.154639,46.8750,1704.778655,707.243015,2.410457,4.536405e+03,70.678414,29.321586,0.024070,0.024029,5,1.778431,0.355686,0.450000,1.250000
6,2,74.540253,62.494373,70.965130,0.159574,31.2500,1474.510816,967.347004,1.524283,2.623368e+03,60.384794,39.615206,0.006219,0.006048,5,0.630056,0.126011,0.450000,6.250000
7,2,79.868637,118.150189,130.902317,0.226667,39.0625,2975.379926,5331.133430,0.558114,8.559546e+03,35.819842,64.180158,0.048503,0.045097,4,0.701856,0.233952,2.166667,1.250000
8,3,83.105462,92.884511,107.248187,0.112903,31.2500,854.456830,2388.034460,0.357808,3.242491e+03,26.351862,73.648138,0.017701,0.018153,9,0.866724,0.096303,1.194444,2.142857
9,3,81.280868,74.733513,105.539186,0.090909,31.2500,932.651988,942.916541,0.989114,2.015015e+03,49.726362,50.273638,-0.156093,-0.157092,30,0.426845,0.014228,0.633333,0.541667
10,3,86.646154,138.161264,175.668367,0.169231,39.0625,431.700871,4918.029023,0.087779,5.349730e+03,8.069583,91.930417,-0.051213,-0.053711,4,0.363875,0.090969,2.000000,1.875000
11,3,100.611354,150.854470,204.018806,0.301887,109.3750,955.965356,3500.739964,0.273075,4.456705e+03,21.450046,78.549954,0.027641,0.027672,5,0.989222,0.197844,1.100000,0.750000
12,4,81.597542,97.301861,133.153928,0.231707,46.8750,1250.410100,1533.086150,0.815616,2.989015e+03,44.922284,55.077716,-0.056913,-0.057351,12,0.223648,0.018637,0.458333,0.568182
13,4,80.338983,91.999068,116.859852,0.205128,46.8750,987.769040,5513.188767,0.179165,6.668597e+03,15.194208,84.805792,-0.052014,-0.052147,42,0.451792,0.011019,0.524390,0.618421
14,4,80.246972,91.368296,121.354899,0.218391,46.8750,1272.863799,3559.875737,0.357558,5.164933e+03,26.338349,73.661651,0.000123,0.000106,47,0.426089,0.009263,0.516304,0.600000
15,4,77.050414,85.204393,113.574989,0.177215,31.2500,1556.362997,1085.434951,1.433861,2.861300e+03,58.913022,41.086978,0.003228,0.002453,38,0.343723,0.009045,0.578947,0.683333
16,6,67.509418,74.834141,65.935332,0.108434,31.2500,923.372314,1269.027275,0.727622,2.443964e+03,42.116972,57.883028,0.263452,0.263326,53,0.294391,0.005555,0.419811,0.609375
17,6,67.257367,56.850529,63.446149,0.166667,31.2500,538.953302,478.133509,1.127203,1.281365e+03,52.989902,47.010098,0.078498,0.078631,26,0.277988,0.010692,0.490385,1.250000
18,6,70.338658,68.248447,79.924137,0.188235,31.2500,1243.000912,2473.736743,0.502479,3.886770e+03,33.443332,66.556668,0.001917,0.001958,12,0.359380,0.029948,0.916667,1.295455
19,6,71.682655,64.572117,71.169223,0.183099,39.0625,1633.557527,1908.931951,0.855744,3.551542e+03,46.113264,53.886736,0.013403,0.014153,4,0.465428,0.116357,1.375000,2.187500
20,8,75.749832,71.422658,84.857206,0.275862,46.8750,1361.097049,2139.474683,0.636183,3.641135e+03,38.882136,61.117864,0.023980,0.032373,10,7.848363,0.784836,1.500000,2.125000
21,8,77.903635,65.477446,71.978615,0.200000,46.8750,950.004233,1941.978591,0.489194,3.039049e+03,32.849581,67.150419,-0.035277,-0.036048,12,10.005040,0.833753,1.750000,2.045455
22,8,79.411414,52.404182,61.775227,0.135922,31.2500,1461.419229,762.482420,1.916660,2.596295e+03,65.714202,34.285798,-0.027772,-0.044292,10,8.631730,0.959081,1.833333,2.031250
23,8,85.431956,117.330030,117.966163,0.236842,62.5000,607.020353,2598.524620,0.233602,5.753685e+03,18.936573,81.063427,0.077647,0.081375,15,24.006784,1.600452,1.183333,2.444444
24,9,90.422698,33.725255,40.050773,0.066116,15.6250,287.767552,461.043427,0.624166,8.602955e+02,38.429932,61.570068,0.039446,0.042149,14,4.237916,0.302708,1.125000,1.270833
25,9,89.569378,35.178929,43.787507,0.034483,15.6250,138.107939,475.908223,0.290199,6.485416e+02,22.492558,77.507442,-0.000213,0.000569,16,5.827479,0.364217,0.968750,1.781250
26,9,89.987879,40.349273,44.242185,0.069565,15.6250,85.540365,251.846215,0.339653,6.105763e+02,25.353814,74.646186,0.022502,0.021484,20,9.200581,0.460029,0.825000,1.062500
27,9,92.003872,51.587883,59.998572,0.142857,31.2500,1040.149576,716.977776,1.450742,1.903051e+03,59.196027,40.803973,0.082611,0.085742,25,15.940095,0.637604,0.770000,1.000000

In [145]:
def remove_outliers_iqr(col, treatment='elim'):
    q1 = col.quantile(0.25)
    q3 = col.quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    if treatment == 'impute':
        return col.clip(lower=lower, upper=upper)
    else:
        return col[(col >= lower) & (col <= upper)]

def remove_outliers_modz(col, treatment='elim'):
    x_mid = col.median()
    mad = abs(col - x_mid).median()
    mz = 0.6745 * (col - x_mid) / mad

    if treatment == 'impute':
        return col.mask(abs(mz) > 3.5, x_mid)
    else:
        return col[abs(mz) <= 3.5]

def remove_outliers_winsor(col, p_low=0.05, p_high=0.95):
    lower = col.quantile(p_low)
    upper = col.quantile(p_high)
    return col.clip(lower=lower, upper=upper)


def norm_with_ref(subjects, feat_mat, ref_mat, normtype=str, outliermeth=outliermeth, outliertreatment=outliertreatment):
        # This line is redundant, eliminate and substitute application on this cell based on preference.
    channel_cols = [
        col for col in ref_mat.columns if col not in ["Subject"]
    ]

    normdata_list = []

    # Data is normalized per subject   ####### Corregir
    for subject in subjects:
        data = feat_mat[feat_mat["Subject"] == subject].copy()
        
        if outliermeth == 'iqr_outlier':
            def outlier_func(col):
                return remove_outliers_iqr(col, outliertreatment)
        elif outliermeth == 'mod_zscore_outlier':
            def outlier_func(col):
                return remove_outliers_modz(col, outliertreatment)
        elif outliermeth == 'winsor_outlier':
            def outlier_func(col):
                return remove_outliers_winsor(col, p_low=0.5, p_high=0.95)

        data[channel_cols] = data[channel_cols].apply(outlier_func)

        ref_data = ref_mat[ref_mat["Subject"] == subject].drop("Subject", axis=1)
        ref_data = ref_data.apply(outlier_func).dropna()

        if normtype == 'zscore':
            ref_mean = np.nanmean(ref_data)
            ref_std = np.nanstd(ref_data)
            data[channel_cols] = (data[channel_cols] - ref_mean) / ref_std
        elif normtype == 'mean':
            ref_mean = np.nanmean(ref_data)
            data[channel_cols] = (data[channel_cols] - ref_mean) / ref_mean
        elif normtype == 'minmax':
            scaler = MinMaxScaler(feature_range=(-0.5,0.5))
            scaler.fit(ref_data[channel_cols])
            scaled = scaler.transform(data[channel_cols])
            #scaled = np.clip(scaled, 0, 1)
            data[channel_cols] = scaled
        elif normtype == 'robust':
            scaler = RobustScaler()
            scaler.fit(ref_data[channel_cols])
            data[channel_cols] = scaler.transform(data[channel_cols])
        normdata_list.append(data.dropna())
    normdata_df = pd.concat(normdata_list, ignore_index=True)

    return normdata_df

norm = norm_with_ref(subjects=subjects, feat_mat=tscene_feat_mat, ref_mat=basal_feat_mat, normtype=normtype)
norm

,Subject,bpm,sdnn,rmssd,pnn50,hr_mad,lf,hf,lf/hf,p_total,lf_nu,hf_nu,mean_eda,mean_tonic,scr_peak_count,scr_sum_amp,scr_mean_amp,scr_mean_risetime,scr_mean_recoverytime
0,1,-0.294365,-0.225873,-0.194539,-0.370833,-0.249668,1.102309,8.652137,-0.371111,9.060170,-0.363410,-0.284347,-0.371200,-0.371200,-0.361041,-0.370134,-0.371048,-0.370350,-0.369772
1,1,-0.294365,-0.221314,-0.187580,-0.370883,-0.255798,2.063414,17.953650,-0.371083,20.068618,-0.361092,-0.286665,-0.371195,-0.371195,-0.361041,-0.370476,-0.371116,-0.370350,-0.368852
2,1,-0.284666,-0.221367,-0.179498,-0.370883,-0.255798,1.102309,9.539106,-0.371111,9.842772,-0.363410,-0.282031,-0.371197,-0.371197,-0.357626,-0.370662,-0.371143,-0.370350,-0.369772
3,1,-0.293957,-0.225873,-0.194539,-0.370867,-0.255798,4.825384,8.652137,-0.369334,9.060170,-0.314625,-0.286665,-0.371200,-0.371200,-0.359195,-0.370662,-0.371143,-0.370330,-0.369627
4,2,-0.294669,-0.297019,-0.296210,-0.365518,-0.323323,9.485376,78.835122,-0.364745,373690.876439,-0.322213,-0.288421,-0.365660,-0.365659,-0.361619,-0.364599,-0.365330,-0.365279,-0.364556
5,2,-0.296086,-0.298290,-0.298881,-0.365530,-0.323323,1.749164,2.480445,-0.363628,5.552056,-0.303206,-0.318783,-0.365662,-0.365662,-0.361167,-0.364157,-0.365364,-0.365279,-0.364556
6,2,-0.296086,-0.298290,-0.298881,-0.365530,-0.326853,1.749164,2.480445,-0.364308,5.552056,-0.311113,-0.318783,-0.365662,-0.365662,-0.361167,-0.364825,-0.365419,-0.365279,-0.360715
7,2,-0.293679,-0.264624,-0.254707,-0.365487,-0.326853,2.323318,4.452334,-0.364745,7.370016,-0.322213,-0.307683,-0.365645,-0.365647,-0.361619,-0.364825,-0.365419,-0.363960,-0.364556
8,3,-0.349129,-0.324768,-0.304153,-0.416482,-0.388650,0.293668,1.923821,-0.416310,2.643350,-0.395648,-0.356105,-0.416580,-0.416580,-0.409440,-0.415905,-0.416518,-0.415645,-0.414923
9,3,-0.349129,-0.324768,-0.304153,-0.416482,-0.388650,0.324746,1.923821,-0.415883,2.643350,-0.379855,-0.356105,-0.416608,-0.416608,-0.395252,-0.416080,-0.416520,-0.415682,-0.415551
10,3,-0.347722,-0.306774,-0.276960,-0.416460,-0.385545,0.293668,3.323632,-0.416344,3.729288,-0.397596,-0.345117,-0.416608,-0.416608,-0.411030,-0.416080,-0.416520,-0.415101,-0.415104
11,3,-0.338286,-0.298197,-0.257805,-0.416370,-0.338038,0.340498,2.366051,-0.416344,3.125923,-0.397596,-0.354157,-0.416574,-0.416573,-0.411030,-0.415823,-0.416449,-0.415682,-0.415551
12,4,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680
13,4,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680
14,4,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680
15,4,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680,-0.118680
16,6,-0.405480,-0.404537,-0.405551,-0.418647,-0.412695,-0.211219,-0.114345,-0.418529,0.155476,-0.410231,-0.407594,-0.418636,-0.418636,-0.409305,-0.418618,-0.418677,-0.418546,-0.418437
17,6,-0.405480,-0.405961,-0.405551,-0.418647,-0.412695,-0.211219,-0.114345,-0.418473,0.155476,-0.408729,-0.407977,-0.418666,-0.418666,-0.413701,-0.418618,-0.418677,-0.418546,-0.418437
18,6,-0.405209,-0.405609,-0.403624,-0.418645,-0.412695,-0.180610,0.038885,-0.418529,0.316118,-0.410231,-0.406182,-0.418672,-0.418672,-0.415042,-0.418612,-0.418675,-0.418505,-0.418433
19,6,-0.404990,-0.405961,-0.405050,-0.418646,-0.411424,-0.117027,-0.053065,-0.418517,0.261543,-0.409849,-0.407977,-0.418672,-0.418672,-0.415042,-0.418595,-0.418661,-0.418431,-0.418287
20,8,-0.333910,-0.340052,-0.328647,-0.400456,-0.360892,0.754803,1.415599,-0.400146,2.690417,-0.367677,-0.346240,-0.400665,-0.400658,-0.391347,-0.392775,-0.399925,-0.399306,-0.398882
21,8,-0.333910,-0.342576,-0.334114,-0.400500,-0.360892,0.580307,1.331768,-0.400208,2.434850,-0.370238,-0.343679,-0.400687,-0.400687,-0.390498,-0.392192,-0.399925,-0.399200,-0.398915
22,8,-0.333270,-0.342576,-0.334114,-0.400500,-0.360892,0.827196,1.331768,-0.399222,2.434850,-0.348315,-0.346240,-0.400687,-0.400687,-0.391347,-0.392775,-0.399872,-0.399140,-0.398915
23,8,-0.328926,-0.306926,-0.304756,-0.400485,-0.349617,0.580307,1.746848,-0.400208,4.214830,-0.370238,-0.333639,-0.400627,-0.400623,-0.388334,-0.382088,-0.399409,-0.399306,-0.398651
24,9,-0.233721,-0.334650,-0.322669,-0.406901,-0.377083,0.144523,0.490880,-0.405834,1.241868,-0.333373,-0.276490,-0.406955,-0.406950,-0.372531,-0.392629,-0.406241,-0.404919,-0.404595
25,9,-0.234137,-0.334650,-0.322669,-0.406901,-0.377083,0.001100,0.505126,-0.406107,1.038937,-0.345905,-0.259297,-0.406971,-0.406970,-0.372531,-0.392629,-0.406241,-0.405174,-0.403763
26,9,-0.234137,-0.329695,-0.322233,-0.406897,-0.377083,0.001100,0.490880,-0.406107,1.038937,-0.345905,-0.263959,-0.406971,-0.406970,-0.368697,-0.389396,-0.406149,-0.405312,-0.404795
27,9,-0.231145,-0.311385,-0.296563,-0.406778,-0.351627,1.370278,0.897868,-0.404488,2.940688,-0.299542,-0.276490,-0.406885,-0.406879,-0.360552,-0.378416,-0.405860,-0.405312,-0.404795

In [146]:
channel_cols = [col for col in basal_feat_mat.columns if col not in ["Subject"]]
basal_outlier_treated = basal_feat_mat
basal_outlier_treated[channel_cols] = basal_feat_mat[channel_cols].apply(remove_outliers_winsor, args=(0.1,0.9,))

In [147]:
tscene_outlier_treated = tscene_feat_mat
tscene_outlier_treated[channel_cols] = tscene_feat_mat[channel_cols].apply(remove_outliers_winsor, args=(0.1,0.9,))

In [148]:
outpath = os.path.join(base_dir, 'Outputs', f'outlier_{outliertreatment}', outliermeth)
basal_outlier_treated.to_csv(os.path.join(outpath,'non-normalized',rf'biometric_feat_mat_scene_{basalscene}_nonnorm.csv'), index=False)
tscene_outlier_treated.to_csv(os.path.join(outpath,'non-normalized',rf'biometric_feat_mat_scene_{targetscene}_nonnorm.csv'), index=False)
norm.to_csv(os.path.join(outpath, rf'biometric_feat_mat_scene_{targetscene}_{normtype}.csv'), index=False)